// [nº, PT, EN, JP kanji, JP kana, JP romaji, ZH hanzi, ZH pinyin, ES, ponte]
window.VOCAB = [
  [1, "um", "one", "一", "いち", "ichi", "一", "yī", "uno", "Mesmo caractere; ichi / yī"],
  [2, "dois", "two", "二", "に", "ni", "二", "èr", "dos", "Mesmo caractere. Ao contar coisas em chinês: 两 liǎng"],
  [3, "três", "three", "三", "さん", "san", "三", "sān", "tres", "Som quase igual"],
  [4, "quatro", "four", "四", "よん", "yon", "四", "sì", "cuatro", "Também し shi em japonês: shi / sì"],
  [5, "cinco", "five", "五", "ご", "go", "五", "wǔ", "cinco", "Mesmo caractere"],
  [6, "seis", "six", "六", "ろく", "roku", "六", "liù", "seis", "Ponte 2: -ku no japonês, sem final no mandarim"],
  [7, "sete", "seven", "七", "なな", "nana", "七", "qī", "siete", "Também しち shichi: shichi / qī"],
  [8, "oito", "eight", "八", "はち", "hachi", "八", "bā", "ocho", "Ponte 2: -chi no japonês, sem final no mandarim"],
  [9, "nove", "nine", "九", "きゅう", "kyū", "九", "jiǔ", "nueve", "kyū / jiǔ"],
  [10, "dez", "ten", "十", "じゅう", "jū", "十", "shí", "diez", "Mesmo caractere"],
  [11, "pessoa", "person", "人", "ひと", "hito", "人", "rén", "persona", "Mesmo caractere: alguém de pé"],
  [12, "homem", "man", "男の人", "おとこのひと", "otoko no hito", "男人", "nánrén", "hombre", "男 = 田 (campo) + 力 (força)"],
  [13, "mulher", "woman", "女の人", "おんなのひと", "onna no hito", "女人", "nǚrén", "mujer", "女 nos dois"],
  [14, "criança", "child", "子供", "こども", "kodomo", "孩子", "háizi", "niño, niña", "子 nos dois"],
  [15, "amigo", "friend", "友達", "ともだち", "tomodachi", "朋友", "péngyou", "amigo", "友 nos dois; espanhol igual ao PT"],
  [16, "água", "water", "水", "みず", "mizu", "水", "shuǐ", "agua", "Mesmo caractere"],
  [17, "fogo", "fire", "火", "ひ", "hi", "火", "huǒ", "fuego", "Mesmo caractere"],
  [18, "montanha", "mountain", "山", "やま", "yama", "山", "shān", "montaña", "on'yomi san (富士山 Fuji-san) ≈ shān"],
  [19, "árvore", "tree", "木", "き", "ki", "树", "shù", "árbol", "Em chinês 木 mù é madeira; 树 contém 木"],
  [20, "rio", "river", "川", "かわ", "kawa", "河", "hé", "río", "Caracteres diferentes; 川 aparece em 四川 Sìchuān"],
  [21, "sol", "sun", "太陽", "たいよう", "taiyō", "太阳", "tàiyáng", "sol", "Mesmo composto (陽 / 阳)"],
  [22, "lua", "moon", "月", "つき", "tsuki", "月亮", "yuèliang", "luna", "月 nos dois"],
  [23, "céu", "sky", "空", "そら", "sora", "天空", "tiānkōng", "cielo", "空 nos dois"],
  [24, "chuva", "rain", "雨", "あめ", "ame", "雨", "yǔ", "lluvia", "Mesmo caractere: gotas caindo do céu"],
  [25, "terra, solo", "earth, soil", "土", "つち", "tsuchi", "土", "tǔ", "tierra", "Mesmo caractere"],
  [26, "onze", "eleven", "十一", "じゅういち", "jūichi", "十一", "shíyī", "once", "Mesma lógica: dez + um"],
  [27, "vinte", "twenty", "二十", "にじゅう", "nijū", "二十", "èrshí", "veinte", "Dois × dez"],
  [28, "cem", "hundred", "百", "ひゃく", "hyaku", "百", "bǎi", "cien", "Ponte 2: -ku"],
  [29, "mil", "thousand", "千", "せん", "sen", "千", "qiān", "mil", "Ponte 2: -n se mantém"],
  [30, "dez mil", "ten thousand", "万", "まん", "man", "万", "wàn", "diez mil", "JP e ZH contam em grupos de 10.000"],
  [31, "dia", "day", "日", "ひ", "hi", "天", "tiān", "día", "日 nos dois (em chinês também 日 rì)"],
  [32, "mês", "month", "月", "つき", "tsuki", "月", "yuè", "mes", "月 = lua = mês nos dois; nas datas がつ gatsu"],
  [33, "ano", "year", "年", "とし", "toshi", "年", "nián", "año", "Nas datas ねん nen: nen / nián"],
  [34, "hoje", "today", "今日", "きょう", "kyō", "今天", "jīntiān", "hoy", "今 = agora nos dois"],
  [35, "amanhã", "tomorrow", "明日", "あした", "ashita", "明天", "míngtiān", "mañana", "明 nos dois; mañana também é manhã"],
  [36, "pai", "father", "父", "ちち", "chichi", "爸爸", "bàba", "padre", "父 nos dois; formal: お父さん otōsan / 父亲 fùqīn"],
  [37, "mãe", "mother", "母", "はは", "haha", "妈妈", "māma", "madre", "母 nos dois; formal: お母さん okāsan / 母亲 mǔqīn"],
  [38, "irmão mais velho", "older brother", "兄", "あに", "ani", "哥哥", "gēge", "hermano mayor", "Palavras diferentes; ao chamar: お兄さん onīsan"],
  [39, "irmã mais velha", "older sister", "姉", "あね", "ane", "姐姐", "jiějie", "hermana mayor", "姉 e 姐 têm o radical 女"],
  [40, "família", "family", "家族", "かぞく", "kazoku", "家人", "jiārén", "familia", "家 nos dois; em chinês 家族 jiāzú é clã"],
  [41, "comer", "eat", "食べる", "たべる", "taberu", "吃", "chī", "comer", "食 = comida nos dois (食物 shíwù)"],
  [42, "beber", "drink", "飲む", "のむ", "nomu", "喝", "hē", "beber", "飲 = 饮, como em 饮料 yǐnliào (bebida)"],
  [43, "ver", "see, look", "見る", "みる", "miru", "看", "kàn", "ver", "見 = 见 jiàn, como em 再见"],
  [44, "ir", "go", "行く", "いく", "iku", "去", "qù", "ir", "Em chinês 行 xíng é “ok, dá certo”"],
  [45, "vir", "come", "来る", "くる", "kuru", "来", "lái", "venir", "Mesmo caractere"],
  [46, "olá", "hello", "こんにちは", "こんにちは", "konnichiwa", "你好", "nǐ hǎo", "hola", "Na fala o tom muda: ní hǎo"],
  [47, "obrigado", "thank you", "ありがとう", "ありがとう", "arigatō", "谢谢", "xièxie", "gracias", "感謝 kansha = 感谢 gǎnxiè (gratidão)"],
  [48, "desculpe", "sorry, excuse me", "すみません", "すみません", "sumimasen", "对不起", "duìbuqǐ", "perdón, lo siento", "Palavras diferentes"],
  [49, "tchau", "goodbye", "さようなら", "さようなら", "sayōnara", "再见", "zàijiàn", "adiós", "再见 = “ver de novo” (见 = 見)"],
  [50, "bom dia", "good morning", "おはよう", "おはよう", "ohayō", "早上好", "zǎoshang hǎo", "buenos días", "好 = bom"],
  [51, "chá", "tea", "お茶", "おちゃ", "ocha", "茶", "chá", "té", "cha / chá, quase igual"],
  [52, "arroz, refeição", "rice, meal", "ご飯", "ごはん", "gohan", "米饭", "mǐfàn", "arroz", "飯 = 饭 (han / fàn)"],
  [53, "carne", "meat", "肉", "にく", "niku", "肉", "ròu", "carne", "Mesmo caractere"],
  [54, "peixe", "fish", "魚", "さかな", "sakana", "鱼", "yú", "pescado", "魚 simplificado vira 鱼; peixe vivo em ES: pez"],
  [55, "ovo", "egg", "卵", "たまご", "tamago", "鸡蛋", "jīdàn", "huevo", "Palavras diferentes"],
  [56, "casa", "house, home", "家", "いえ", "ie", "家", "jiā", "casa", "Mesmo caractere"],
  [57, "escola", "school", "学校", "がっこう", "gakkō", "学校", "xuéxiào", "escuela", "Mesmo composto; gaku / xué"],
  [58, "loja", "shop, store", "店", "みせ", "mise", "商店", "shāngdiàn", "tienda", "店 nos dois"],
  [59, "empresa", "company", "会社", "かいしゃ", "kaisha", "公司", "gōngsī", "empresa", "会社 invertido é 社会: sociedade nas duas línguas"],
  [60, "estação", "station", "駅", "えき", "eki", "车站", "chēzhàn", "estación", "Palavras diferentes"],
  [61, "hora (em ponto)", "o'clock", "時", "じ", "ji", "点", "diǎn", "hora", "時 = 时, como em 时间 shíjiān = 時間 jikan"],
  [62, "minuto", "minute", "分", "ふん", "fun", "分", "fēn", "minuto", "Mesmo caractere (às vezes ぷん pun)"],
  [63, "agora", "now", "今", "いま", "ima", "现在", "xiànzài", "ahora", "今 aparece em 今天"],
  [64, "manhã", "morning", "朝", "あさ", "asa", "早上", "zǎoshang", "mañana", "Palavras diferentes; ES mañana = manhã e amanhã"],
  [65, "noite", "night, evening", "夜", "よる", "yoru", "晚上", "wǎnshang", "noche", "晩 ban = 晚 wǎn; 夜 nos dois"],
  [66, "grande", "big", "大きい", "おおきい", "ōkii", "大", "dà", "grande", "大 = pessoa de braços abertos"],
  [67, "pequeno", "small", "小さい", "ちいさい", "chiisai", "小", "xiǎo", "pequeño", "小 nos dois"],
  [68, "bom", "good", "いい", "いい", "ii", "好", "hǎo", "bueno", "Em japonês 好き suki é gostar"],
  [69, "novo", "new", "新しい", "あたらしい", "atarashii", "新", "xīn", "nuevo", "on'yomi shin ≈ xīn"],
  [70, "velho (coisa)", "old", "古い", "ふるい", "furui", "旧", "jiù", "viejo", "古 = antigo nos dois (古代); pessoas em ZH: 老 lǎo"],
  [71, "fazer", "do", "する", "する", "suru", "做", "zuò", "hacer", "Palavras diferentes"],
  [72, "dizer", "say", "言う", "いう", "iu", "说", "shuō", "decir", "言 vira o radical 讠 de 说"],
  [73, "saber", "know", "知る", "しる", "shiru", "知道", "zhīdao", "saber", "知 nos dois"],
  [74, "querer", "want", "欲しい", "ほしい", "hoshii", "要", "yào", "querer", "Querer fazer: 〜たい / 想 xiǎng"],
  [75, "haver, ter", "there is, have", "ある", "ある", "aru", "有", "yǒu", "haber, tener", "JP separa vivo (いる iru) × não vivo (ある); ZH usa 有 para tudo"],
  [76, "livro", "book", "本", "ほん", "hon", "书", "shū", "libro", "Armadilha: em chinês 本 běn é o contador de livros"],
  [77, "telefone", "telephone", "電話", "でんわ", "denwa", "电话", "diànhuà", "teléfono", "den / diàn, wa / huà"],
  [78, "computador", "computer", "パソコン", "パソコン", "pasokon", "电脑", "diànnǎo", "computadora, ordenador", "電 = eletricidade; 电脑 = “cérebro elétrico”"],
  [79, "mesa", "table, desk", "机", "つくえ", "tsukue", "桌子", "zhuōzi", "mesa", "Armadilha: em chinês 机 jī é máquina (手机 celular)"],
  [80, "carro", "car", "車", "くるま", "kuruma", "车", "chē", "coche, carro", "車 simplificado vira 车; também 汽车 qìchē"],
  [81, "branco", "white", "白い", "しろい", "shiroi", "白", "bái", "blanco", "Mesmo caractere"],
  [82, "preto", "black", "黒い", "くろい", "kuroi", "黑", "hēi", "negro", "黒 e 黑: quase idênticos"],
  [83, "vermelho", "red", "赤い", "あかい", "akai", "红", "hóng", "rojo", "Palavras diferentes"],
  [84, "azul", "blue", "青い", "あおい", "aoi", "蓝", "lán", "azul", "青 cobre azul e verde em JP; em ZH 青 qīng é verde-azulado"],
  [85, "cor", "color", "色", "いろ", "iro", "颜色", "yánsè", "color", "色 nos dois"],
  [86, "domingo", "Sunday", "日曜日", "にちようび", "nichiyōbi", "星期天", "xīngqītiān", "domingo", "日 = sol, como Sunday"],
  [87, "segunda-feira", "Monday", "月曜日", "げつようび", "getsuyōbi", "星期一", "xīngqīyī", "lunes", "月 = lua, como Monday e lunes"],
  [88, "terça-feira", "Tuesday", "火曜日", "かようび", "kayōbi", "星期二", "xīngqī'èr", "martes", "火星 = Marte, como martes"],
  [89, "quarta-feira", "Wednesday", "水曜日", "すいようび", "suiyōbi", "星期三", "xīngqīsān", "miércoles", "水星 = Mercúrio, como miércoles"],
  [90, "quinta-feira", "Thursday", "木曜日", "もくようび", "mokuyōbi", "星期四", "xīngqīsì", "jueves", "木星 = Júpiter, como jueves"],
  [91, "sexta-feira", "Friday", "金曜日", "きんようび", "kin'yōbi", "星期五", "xīngqīwǔ", "viernes", "金星 = Vênus, como viernes"],
  [92, "sábado", "Saturday", "土曜日", "どようび", "doyōbi", "星期六", "xīngqīliù", "sábado", "土星 = Saturno, como Saturday"],
  [93, "semana", "week", "週", "しゅう", "shū", "星期", "xīngqī", "semana", "週 = 周 zhōu (shū / zhōu)"],
  [94, "fim de semana", "weekend", "週末", "しゅうまつ", "shūmatsu", "周末", "zhōumò", "fin de semana", "Mesmo composto"],
  [95, "dinheiro", "money", "お金", "おかね", "okane", "钱", "qián", "dinero", "金 é o radical 钅 de 钱"],
  [96, "ônibus", "bus", "バス", "バス", "basu", "公交车", "gōngjiāochē", "autobús", "Japonês importou do inglês"],
  [97, "trem", "train", "電車", "でんしゃ", "densha", "火车", "huǒchē", "tren", "Armadilha: 汽車 em JP é trem a vapor; em ZH é carro"],
  [98, "andar (a pé)", "walk", "歩く", "あるく", "aruku", "走", "zǒu", "caminar", "Armadilha: 走る em JP é correr"],
  [99, "correr", "run", "走る", "はしる", "hashiru", "跑", "pǎo", "correr", "Par com o 98: grave os dois juntos"],
  [100, "avião", "airplane", "飛行機", "ひこうき", "hikōki", "飞机", "fēijī", "avión", "飛 = 飞 (voar), 機 = 机 (máquina)"]
];
