// [semana, tema da quadra, novos por dia útil, japonês, chinês, inglês, espanhol]
window.WEEKS = [
  [1, "Números 1–10, pessoas, natureza, céu", 5, "Hiragana: as 46 básicas", "Pinyin: 4 tons, iniciais e finais", "Teste EF SET; sons críticos: th, vogais curtas e longas, consoantes finais, -ed", "Passivo: leitura no verso dos cartões"],
  [2, "Números grandes, tempo, família, verbos, cumprimentos", 5, "Hiragana completo: dakuten, yōon, っ, vogais longas", "Pares de tons; HSK1 L1–3; ordem de traço", "Tonicidade, weak forms, linking, contrações", "Passivo"],
  [3, "Comida, lugares, horas, adjetivos, verbos", 5, "Katakana completo; Genki L1 (X は Y です, か, の)", "HSK1 L4–7 (的, 呢, 几, 会, datas); radicais simplificados", "Pitch pessoal de 1 min; verbos de estado × ação (I think / I'm thinking)", "Passivo"],
  [4, "Objetos, cores, dias da semana, transporte", 5, "Genki L2 (これ/それ/あれ, この/その, ここ/そこ, も, じゃないです)", "HSK1 L8–11 (想, 多少, 在, 有, 能, horas)", "Diagnóstico: texto de 200 palavras, Claude mapeia seus erros recorrentes", "Passivo"],
  [5, "Escola e trabalho; compras e dinheiro", 8, "Genki L3: verbos em ます, grupos de verbos, partículas で/に/へ/を", "HSK1 L12–15 (怎么样, 在…呢, 了, 是…的)", "Narrativas: past simple, past continuous e past perfect", "Passivo"],
  [6, "Cidade e direções; clima", 8, "Genki L3: 〜ませんか, advérbios de frequência, horários", "Revisão HSK1 + simulado HSK 1", "Present perfect simple × continuous (I've been working)", "Passivo"],
  [7, "Rotina e tempo livre", 8, "Genki L4: があります/がいます, posição (上, 下, 中), passado de です", "HSK2 L1–2 (最, 要, 每天, 为什么)", "Futuro avançado: future continuous e future perfect", "Passivo"],
  [8, "Roupas, corpo, saúde", 8, "Genki L4: passado em ました, も, 〜時間, と", "HSK2 L3–4 (frases com 的, 一下, 已经…了)", "Small talk e networking: perguntas abertas e follow-ups", "Passivo"],
  [9, "Emoções e personalidade", 8, "Genki L5: adjetivos い e な no presente e passado, 好き/きらい", "HSK2 L5–6 (吧, 还, 因为…所以, 了 de mudança)", "Condicionais 0 a 3 e mistas", "Pronúncia: j, g, ll/y, z/c, r/rr; sem vogais nasais"],
  [10, "Viagem, hotel, aeroporto", 8, "Genki L5: 〜ましょう, 〜ましょうか, contadores", "HSK2 L7–8 (离, 让, verbo repetido 想想)", "Diplomacia: pedir, recusar e discordar com educação", "Falsos amigos PT–ES I"],
  [11, "Restaurante e sabores", 8, "Genki L6: forma て, 〜てください, 〜てもいいです, 〜てはいけません", "HSK2 L9–10 (complementos de resultado 完/到/好, 别…了)", "Phrasal verbs I: os mais usados em reuniões", "Presente: irregulares que diferem do PT"],
  [12, "Natureza e animais", 8, "Genki L6: duas ações com て, 〜から, 〜ましょうか de oferta", "HSK2 L11–12 (比, 得 de grau)", "Argumentação: opinião, hedging e contra-argumento", "Gênero diferente do PT (el viaje, la leche, la nariz)"],
  [13, "Checkpoint dia 90", 0, "Revisão L1–6 + teste de kana", "Revisão HSK2 L1–12", "Reteste EF SET + gravação de 3 min", "Primeira conversa de 10 min"],
  [14, "Tecnologia e internet", 10, "Genki L7: 〜ている, descrever pessoas, forma て de adjetivos, 〜に行く", "HSK2 L13–14 (着, 往, 过, 虽然…但是)", "Voz passiva e estruturas impessoais (it is said that)", "Pretérito indefinido × perfecto (uso diferente do PT)"],
  [15, "Trabalho e escritório", 10, "Genki L7: contar pessoas, vocabulário de família", "HSK2 L15 (要…了, 快…了) + revisão", "Orações relativas e reduzidas", "Pronomes: lo, la, le, se lo"],
  [16, "Negócios e dinheiro", 10, "Genki L8: formas curtas, fala informal, 〜と思います", "Simulado HSK 2", "Verbos de relato: claim, suggest, deny, admit", "Gustar e verbos parecidos"],
  [17, "Família e relações", 10, "Genki L8: 〜と言っていました, 〜ないでください, 〜のが好き, 何か/何も", "HSK3 L1 (打算, 一…也不)", "E-mails profissionais: tom, clareza e follow-up", "Heterotônicos (nivel, cerebro, policía)"],
  [18, "Casa e tarefas", 10, "Genki L9: passado em forma curta, verbos qualificando substantivos", "HSK3 L2 (complementos direcionais 来/去)", "Reuniões: abrir, interromper, resumir", "Imperfecto"],
  [19, "Saúde e médico", 10, "Genki L9: まだ〜ていません, 〜から de razão", "HSK3 L3 (着 de estado, 还是 × 或者)", "Números, gráficos e tendências", "Futuro e condicional"],
  [20, "Esportes e hobbies", 10, "Genki L10: comparar dois itens e três ou mais", "HSK3 L4 (又…又, 越来越)", "Phrasal verbs II", "Falsos amigos PT–ES II"],
  [21, "Estudo e escola", 10, "Genki L10: 〜つもり, adjetivo + なる, どこかに/どこにも", "HSK3 L5 (一…就, 刚/刚才)", "Pronúncia II: schwa, ritmo e entonação", "Por × para"],
  [22, "Cidade e serviços", 10, "Genki L11: 〜たい, 〜たり〜たりする", "HSK3 L6 (complemento potencial: 找不到)", "Collocations: make/do, have/take, strong/heavy", "Muy × mucho, apócopes (buen, gran)"],
  [23, "Comunicação: ligar, enviar, responder", 10, "Genki L11: 〜ことがある, A や B", "HSK3 L7 (duração + 了)", "Modais de dedução (must have, might have)", "Subjuntivo presente"],
  [24, "Tempo e frequência (advérbios)", 10, "Genki L12: 〜んです, 〜すぎる, 〜ほうがいいです", "HSK3 L8 (interrogativos indefinidos)", "Storytelling: contar um caso em 3 min", "Imperativo"],
  [25, "Verbos abstratos: decidir, pensar, esperar", 10, "Genki L12: 〜ので, 〜なければいけません, 〜でしょう", "HSK3 L9 (跟…一样, 比 com quantidade)", "Conectores e coesão (however, whereas, thus)", "Espanha × América: vosotros, ustedes, voseo"],
  [26, "Checkpoint dia 180", 0, "Revisão Genki I + simulado JLPT N5", "Revisão HSK3 L1–9", "Reteste EF SET + gravação de 3 min", "Conversa de 15 min"],
  [27, "Emoções e opinião", 10, "Genki L13: forma potencial, 〜し", "HSK3 L10 (比…多了, 更)", "Negociação I: posições e concessões", "Subjuntivo imperfeito"],
  [28, "Sociedade e trabalho", 10, "Genki L13: 〜そうです (parece), 〜てみる, なら", "HSK3 L11 (把)", "Negociação II: hedging e suavizar", "Condicionais"],
  [29, "Natureza e meio ambiente", 10, "Genki L14: ほしい, 〜かもしれません, あげる/くれる/もらう", "HSK3 L12 (把…放在/给)", "Pitch de 60 segundos", "Discurso indireto"],
  [30, "Mídia e notícias", 10, "Genki L14: 〜たらどうですか, も/しか com números", "HSK3 L13 (direcionais compostos: 走回来)", "Pitch de 3 min + perguntas", "Perífrases: ir a, acabar de, volver a"],
  [31, "Economia: preço, mercado, empresa", 10, "Genki L15: forma volitiva, 〜と思っています", "HSK3 L14 (把 + direcional: 拿过来)", "Vocabulário acadêmico (Academic Word List)", "Expressões idiomáticas"],
  [32, "Ciência e tecnologia", 10, "Genki L15: 〜ておく, orações que qualificam substantivos", "HSK3 L15 (除了…以外)", "Escrita: opinião em 300 palavras", "Espanhol de negócios I"],
  [33, "Governo e lei (básico)", 10, "Genki L16: 〜てあげる/くれる/もらう, 〜ていただけませんか", "HSK3 L16 (得 + oração: 累得…)", "Escuta: sotaques UK, US, AU, Índia e não nativos", "E-mail formal"],
  [34, "Cultura e arte", 10, "Genki L16: 〜といい, 〜時, 〜てすみませんでした", "HSK3 L17 (谁都, 什么都)", "Inversão e ênfase: cleft sentences", "Gírias: México, Argentina, Espanha"],
  [35, "Geografia e países", 10, "Genki L17: 〜そうです (ouvi dizer), 〜って, 〜たら", "HSK3 L18 (只要…就, 会…的)", "Idioms de negócios frequentes", "Leitura de notícia"],
  [36, "Corpo e saúde II", 10, "Genki L17: 〜なくてもいいです, 〜みたいです, 〜前に/〜てから", "HSK3 L19 (出来, 起来 em sentido figurado)", "Wish, if only, arrependimentos", "Podcast nativo"],
  [37, "Conectores: porque, portanto, porém", 10, "Genki L18: pares transitivo/intransitivo, 〜てしまう", "HSK3 L20 (被)", "Debate: argumentar e refutar", "Debate em espanhol"],
  [38, "Verbos de mudança: aumentar, cair, mudar", 10, "Genki L18: 〜と, 〜ながら, 〜ばよかったです", "Revisão HSK3 + Mandarin Companion nível 1", "Explicar um sistema técnico em 5 min", "Espanhol de negócios II"],
  [39, "Checkpoint dia 270", 0, "Revisão Genki L13–18", "Simulado HSK 3", "Reteste EF SET + gravação de 3 min", "Resumo oral de um vídeo nativo"],
  [40, "Negócios: contrato, cliente, reunião", 10, "Genki L19: honoríficos, 〜てくれてありがとう", "HSK4 上 L1", "Escrever documentação e specs", "Série com legenda em espanhol"],
  [41, "Engenharia e construção", 10, "Genki L19: 〜てよかったです, 〜はずです", "HSK4 上 L2", "Linguagem vaga e nuance (sort of, arguably)", "Escrita: texto de opinião"],
  [42, "Software, dados e IA", 10, "Genki L20: expressões humildes e extramodestas", "HSK4 上 L3", "Registro formal × informal", "Pitch em espanhol"],
  [43, "Ideias abstratas: problema, solução, resultado", 10, "Genki L20: perguntas embutidas, 〜という, 〜やすい/〜にくい", "HSK4 上 L4", "Humor, ironia e understatement", "Conversa livre de 20 min"],
  [44, "Expressões de 4 caracteres (四字熟語 / 成语)", 10, "Genki L21: passiva, 〜てある", "HSK4 上 L5", "Leitura rápida de textos longos", "Leitura de conto"],
  [45, "Emoções e nuances", 10, "Genki L21: 〜間に, adjetivo + する, 〜てほしい", "HSK4 上 L6", "Escrita: relatório de 1 página", "Entrevista simulada"],
  [46, "Internet e redes", 10, "Genki L22: causativa, 〜なさい", "HSK4 上 L7", "Falar de si por 10 min", "Negociação"],
  [47, "Finanças pessoais", 10, "Genki L22: 〜ば, 〜のに, 〜のような", "HSK4 上 L8", "Conversa livre de 30 min", "Apresentação técnica"],
  [48, "Política e sociedade", 10, "Genki L23: causativa-passiva, 〜ても", "HSK4 上 L9", "Log de erros: os 20 mais frequentes", "Log de erros"],
  [49, "História e tradição", 10, "Genki L23: 〜ことにする, 〜まで, 〜方", "HSK4 上 L10", "Apresentação de 10 min preparada", "Conversa de 30 min"],
  [50, "Revisão geral", 0, "Revisão Genki II", "Revisão HSK3 + HSK4 上", "Simulado EF SET", "Revisão dos temas S9–S49"],
  [51, "Revisão de lacunas", 0, "Simulado JLPT N4", "Simulado HSK 3 (HSK 4 no Turbo)", "Apresentação final gravada", "Simulado DELE B1 (amostra)"],
  [52, "Checkpoint final dia 365", 0, "Gravação final de 3 min", "Gravação final de 3 min", "EF SET final", "Gravação final de 3 min"]
];

window.TRIMESTRES = [
  { nome: "Trimestre 1", de: 1, ate: 13, lead: "A fundação: sistemas de escrita, tons e sons nas primeiras 3 semanas, depois os livros-base. Termina com ~420 conceitos, HSK 1 fechado e Genki até a L6." },
  { nome: "Trimestre 2", de: 14, ate: 26, lead: "O volume: 10 conceitos por dia útil, Genki I até o fim (nível N5) e entrada no HSK 3. Nas lições do HSK 3 a coluna indica a lição e o foco dela; se sua edição ordenar diferente, siga o livro." },
  { nome: "Trimestre 3", de: 27, ate: 39, lead: "A produção: Genki II, HSK 3 até o fim e o inglês entra em negociação, pitch e debate. O espanhol sai da gramática básica e vai para input nativo." },
  { nome: "Trimestre 4", de: 40, ate: 52, lead: "A fluência: fim do Genki II (nível N4), HSK 4 上, inglês técnico e espanhol em conversa livre. As 3 últimas semanas são revisão, simulados e a gravação final." }
];

// [dia, quadra, japonês, chinês, inglês]
window.DAYS = [
  [1, "Números 1–5 (一 二 三 四 五)", "Hiragana: linhas あ e か; escrever cada kana 5 vezes", "Pinyin: os 4 tons + neutro; finais simples a o e i u ü", "Teste EF SET (50 min; hoje o bloco é maior)"],
  [2, "Números 6–10 (六 七 八 九 十)", "Linhas さ e た", "Iniciais b p m f d t n l; aspiradas × não aspiradas", "Som th /θ/ e /ð/ (think, this); gravar 10 palavras"],
  [3, "Pessoas: pessoa, homem, mulher, criança, amigo", "Linhas な e は", "Iniciais g k h, j q x", "Vogais curtas × longas: ship/sheep, full/fool"],
  [4, "Natureza: água, fogo, montanha, árvore, rio", "Linhas ま, や e ら (o r de caro)", "Iniciais zh ch sh r, z c s", "Consoantes finais sem o i extra: big, stop, good"],
  [5, "Céu: sol, lua, céu, chuva, terra", "わ, を, ん + revisão das 46", "Finais compostas: ai ei ao ou, an en ang eng ong", "Terminação -ed: worked /t/, played /d/, wanted /ɪd/"],
  [6, "Consolidação, 0 novos", "Ler 30 palavras só em hiragana; configurar teclado japonês", "Ler 30 sílabas com tom; mudança do 3º tom (你好 ní hǎo) e de 不 e 一", "Shadowing de 1 min"],
  [7, "Teste", "46 kana em menos de 2 min", "Ditado de 20 sílabas com tom", "Gravar 1 min se apresentando (guarde para o dia 365)"],
  [8, "Números grandes: onze, vinte, cem, mil, dez mil", "Dakuten e handakuten: が ざ だ ば ぱ", "20 combinações de tons em pares", "Tonicidade: PHOtograph, phoTOgraphy, photoGRAphic"],
  [9, "Tempo: dia, mês, ano, hoje, amanhã", "Yōon: きゃ, しゅ, ちょ", "HSK1 L1 (你好, 对不起, 没关系)", "Weak forms: to, for, of, and, can"],
  [10, "Família: pai, mãe, irmão mais velho, irmã mais velha, família", "っ pequeno e vogais longas (おかあさん)", "HSK1 L2 (谢谢, 不客气, 再见)", "Linking: an apple, pick it up"],
  [11, "Verbos I: comer, beber, ver, ir, vir", "Ler 50 palavras reais em hiragana", "HSK1 L3 (叫, 什么, 是, 吗)", "Fala rápida: gonna, wanna, gotta"],
  [12, "Cumprimentos: olá, obrigado, desculpe, tchau, bom dia", "Escrever à mão todas as kana", "Hanzi: 8 regras de ordem de traço; radicais 亻 口 女 木 氵", "Shadowing de 10 min (ritmo e entonação)"],
  [13, "Consolidação, 0 novos", "Ler um livro graduado nível 0 (Tadoku)", "Shadowing dos diálogos L1–3", "Diário de 5 frases corrigido pelo Claude"],
  [14, "Teste", "Todas as kana e combinações em menos de 3 min", "Ditado de pinyin + diálogos L1–3 de memória", "Gravar 1 min lendo; comparar com o D7"],
  [15, "Comida: chá, arroz, carne, peixe, ovo", "Katakana ア a ノ", "HSK1 L4 (的, 呢, 谁)", "Pitch pessoal de 1 min: quem você é e o que faz (gravar)"],
  [16, "Lugares: casa, escola, loja, empresa, estação", "Katakana ハ a ン", "HSK1 L5 (números até 99, 几, 岁)", "Verbos de estado × ação: I think / I'm thinking"],
  [17, "Horas: hora, minuto, agora, manhã, noite", "Katakana: dakuten e combinações estrangeiras (ティ, ファ)", "HSK1 L6 (会, 怎么)", "Descrever sua empresa por 2 min"],
  [18, "Adjetivos: grande, pequeno, bom, novo, velho", "Vogal longa ー e empréstimos: パン (pão), ボタン (botão), コーヒー", "Radicais simplificados: 讠 = 言, 钅 = 金, 饣 = 食", "Perguntas indiretas: Could you tell me where…?"],
  [19, "Verbos II: fazer, dizer, saber, querer, haver/ter", "Genki L1: X は Y です, か, の + vocabulário", "HSK1 L7 (datas: 月, 号, 星期)", "Small talk: 10 perguntas abertas + follow-ups"],
  [20, "Consolidação, 0 novos", "Ler 30 palavras em katakana (cardápios, marcas)", "Shadowing L4–7", "Diário de 5 frases"],
  [21, "Teste", "Katakana em menos de 3 min + diálogo do Genki L1", "Diálogos L4–7 + ditado", "Gravação de 2 min: meu trabalho"],
  [22, "Objetos: livro, telefone, computador, mesa, carro", "Genki L2: これ/それ/あれ/どれ", "HSK1 L8 (想, 多少, 块)", "Diagnóstico: texto de 200 palavras sobre sua semana; Claude marca os erros"],
  [23, "Cores: branco, preto, vermelho, azul, cor", "Genki L2: この/その/あの, ここ/そこ/あそこ", "HSK1 L9 (在 + lugar, 哪儿)", "Estudar os 3 erros mais frequentes do texto"],
  [24, "Dias da semana: domingo a quinta", "Genki L2: だれの, も, じゃないです", "HSK1 L10 (有, 能, 请)", "Preposições que brasileiro erra: depend on, married to, arrive in/at"],
  [25, "Sexta, sábado, semana, fim de semana, dinheiro", "Genki L2: preços com 円, 百, 千", "Hanzi: escrever à mão os caracteres do mês", "Reescrever o texto do D22 sem os erros"],
  [26, "Transporte: ônibus, trem, andar, correr, avião", "Genki L2: diálogo de memória + workbook", "HSK1 L11 (horas: 点, 分, 前)", "E-mail profissional curto: pedir, confirmar, remarcar"],
  [27, "Consolidação, 0 novos", "Workbook do Genki L1–2", "Shadowing L8–11", "Diário + conversa (Claude ou italki)"],
  [28, "Teste do mês", "Genki L1–2 + todas as kana", "HSK1 L1–11 + ditado", "Gravação de 3 min; comparar com o D7"],
  [29, "Escola e trabalho (8, lote da S5)", "Genki L3: verbos em ます, grupos ru e u", "HSK1 L12 (怎么样, 太…了)", "Narrativas: past simple × past continuous (contar um caso)"],
  [30, "Escola e trabalho (8)", "Genki L3: partículas で, に, へ, を", "HSK1 L13 (在…呢)", "Past perfect: o que já tinha acontecido antes"]
];
