// A trilha: níveis → unidades → itens.
// Cada item: [português, inglês, japonês (escrita), japonês (kana), japonês (romaji), chinês (hanzi), chinês (pinyin)]
// A mesma trilha é percorrida separadamente em cada língua (inglês, japonês, chinês).
window.TRILHA = [
  {
    nivel: "Básico",
    descricao: "As primeiras 100 palavras: números, pessoas, natureza, comida, lugares e o dia a dia.",
    unidades: [
      { titulo: "Números 1 a 5", itens: [
        ["um","one","一","いち","ichi","一","yī"],
        ["dois","two","二","に","ni","二","èr"],
        ["três","three","三","さん","san","三","sān"],
        ["quatro","four","四","よん","yon","四","sì"],
        ["cinco","five","五","ご","go","五","wǔ"],
      ] },
      { titulo: "Números 6 a 10", itens: [
        ["seis","six","六","ろく","roku","六","liù"],
        ["sete","seven","七","なな","nana","七","qī"],
        ["oito","eight","八","はち","hachi","八","bā"],
        ["nove","nine","九","きゅう","kyū","九","jiǔ"],
        ["dez","ten","十","じゅう","jū","十","shí"],
      ] },
      { titulo: "Pessoas", itens: [
        ["pessoa","person","人","ひと","hito","人","rén"],
        ["homem","man","男の人","おとこのひと","otoko no hito","男人","nánrén"],
        ["mulher","woman","女の人","おんなのひと","onna no hito","女人","nǚrén"],
        ["criança","child","子供","こども","kodomo","孩子","háizi"],
        ["amigo","friend","友達","ともだち","tomodachi","朋友","péngyou"],
      ] },
      { titulo: "Natureza", itens: [
        ["água","water","水","みず","mizu","水","shuǐ"],
        ["fogo","fire","火","ひ","hi","火","huǒ"],
        ["montanha","mountain","山","やま","yama","山","shān"],
        ["árvore","tree","木","き","ki","树","shù"],
        ["rio","river","川","かわ","kawa","河","hé"],
      ] },
      { titulo: "Céu e clima", itens: [
        ["sol","sun","太陽","たいよう","taiyō","太阳","tàiyáng"],
        ["lua","moon","月","つき","tsuki","月亮","yuèliang"],
        ["céu","sky","空","そら","sora","天空","tiānkōng"],
        ["chuva","rain","雨","あめ","ame","雨","yǔ"],
        ["terra, solo","earth, soil","土","つち","tsuchi","土","tǔ"],
      ] },
      { titulo: "Números grandes", itens: [
        ["onze","eleven","十一","じゅういち","jūichi","十一","shíyī"],
        ["vinte","twenty","二十","にじゅう","nijū","二十","èrshí"],
        ["cem","hundred","百","ひゃく","hyaku","百","bǎi"],
        ["mil","thousand","千","せん","sen","千","qiān"],
        ["dez mil","ten thousand","万","まん","man","万","wàn"],
      ] },
      { titulo: "Calendário", itens: [
        ["dia","day","日","ひ","hi","天","tiān"],
        ["mês","month","月","つき","tsuki","月","yuè"],
        ["ano","year","年","とし","toshi","年","nián"],
        ["hoje","today","今日","きょう","kyō","今天","jīntiān"],
        ["amanhã","tomorrow","明日","あした","ashita","明天","míngtiān"],
      ] },
      { titulo: "Família", itens: [
        ["pai","father","父","ちち","chichi","爸爸","bàba"],
        ["mãe","mother","母","はは","haha","妈妈","māma"],
        ["irmão mais velho","older brother","兄","あに","ani","哥哥","gēge"],
        ["irmã mais velha","older sister","姉","あね","ane","姐姐","jiějie"],
        ["família","family","家族","かぞく","kazoku","家人","jiārén"],
      ] },
      { titulo: "Verbos de movimento", itens: [
        ["comer","eat","食べる","たべる","taberu","吃","chī"],
        ["beber","drink","飲む","のむ","nomu","喝","hē"],
        ["ver","see, look","見る","みる","miru","看","kàn"],
        ["ir","go","行く","いく","iku","去","qù"],
        ["vir","come","来る","くる","kuru","来","lái"],
      ] },
      { titulo: "Cumprimentos", itens: [
        ["olá","hello","こんにちは","こんにちは","konnichiwa","你好","nǐ hǎo"],
        ["obrigado","thank you","ありがとう","ありがとう","arigatō","谢谢","xièxie"],
        ["desculpe","sorry, excuse me","すみません","すみません","sumimasen","对不起","duìbuqǐ"],
        ["tchau","goodbye","さようなら","さようなら","sayōnara","再见","zàijiàn"],
        ["bom dia","good morning","おはよう","おはよう","ohayō","早上好","zǎoshang hǎo"],
      ] },
      { titulo: "Comida", itens: [
        ["chá","tea","お茶","おちゃ","ocha","茶","chá"],
        ["arroz, refeição","rice, meal","ご飯","ごはん","gohan","米饭","mǐfàn"],
        ["carne","meat","肉","にく","niku","肉","ròu"],
        ["peixe","fish","魚","さかな","sakana","鱼","yú"],
        ["ovo","egg","卵","たまご","tamago","鸡蛋","jīdàn"],
      ] },
      { titulo: "Lugares", itens: [
        ["casa","house, home","家","いえ","ie","家","jiā"],
        ["escola","school","学校","がっこう","gakkō","学校","xuéxiào"],
        ["loja","shop, store","店","みせ","mise","商店","shāngdiàn"],
        ["empresa","company","会社","かいしゃ","kaisha","公司","gōngsī"],
        ["estação","station","駅","えき","eki","车站","chēzhàn"],
      ] },
      { titulo: "Horas do dia", itens: [
        ["hora (em ponto)","o'clock","時","じ","ji","点","diǎn"],
        ["minuto","minute","分","ふん","fun","分","fēn"],
        ["agora","now","今","いま","ima","现在","xiànzài"],
        ["manhã","morning","朝","あさ","asa","早上","zǎoshang"],
        ["noite","night, evening","夜","よる","yoru","晚上","wǎnshang"],
      ] },
      { titulo: "Descrever coisas", itens: [
        ["grande","big","大きい","おおきい","ōkii","大","dà"],
        ["pequeno","small","小さい","ちいさい","chiisai","小","xiǎo"],
        ["bom","good","いい","いい","ii","好","hǎo"],
        ["novo","new","新しい","あたらしい","atarashii","新","xīn"],
        ["velho (coisa)","old","古い","ふるい","furui","旧","jiù"],
      ] },
      { titulo: "Verbos do dia a dia", itens: [
        ["fazer","do","する","する","suru","做","zuò"],
        ["dizer","say","言う","いう","iu","说","shuō"],
        ["saber","know","知る","しる","shiru","知道","zhīdao"],
        ["querer","want","欲しい","ほしい","hoshii","要","yào"],
        ["haver, ter","there is, have","ある","ある","aru","有","yǒu"],
      ] },
      { titulo: "Objetos", itens: [
        ["livro","book","本","ほん","hon","书","shū"],
        ["telefone","telephone","電話","でんわ","denwa","电话","diànhuà"],
        ["computador","computer","パソコン","パソコン","pasokon","电脑","diànnǎo"],
        ["mesa","table, desk","机","つくえ","tsukue","桌子","zhuōzi"],
        ["carro","car","車","くるま","kuruma","车","chē"],
      ] },
      { titulo: "Cores", itens: [
        ["branco","white","白い","しろい","shiroi","白","bái"],
        ["preto","black","黒い","くろい","kuroi","黑","hēi"],
        ["vermelho","red","赤い","あかい","akai","红","hóng"],
        ["azul","blue","青い","あおい","aoi","蓝","lán"],
        ["cor","color","色","いろ","iro","颜色","yánsè"],
      ] },
      { titulo: "Dias da semana I", itens: [
        ["domingo","Sunday","日曜日","にちようび","nichiyōbi","星期天","xīngqītiān"],
        ["segunda-feira","Monday","月曜日","げつようび","getsuyōbi","星期一","xīngqīyī"],
        ["terça-feira","Tuesday","火曜日","かようび","kayōbi","星期二","xīngqī'èr"],
        ["quarta-feira","Wednesday","水曜日","すいようび","suiyōbi","星期三","xīngqīsān"],
        ["quinta-feira","Thursday","木曜日","もくようび","mokuyōbi","星期四","xīngqīsì"],
      ] },
      { titulo: "Semana e dinheiro", itens: [
        ["sexta-feira","Friday","金曜日","きんようび","kin'yōbi","星期五","xīngqīwǔ"],
        ["sábado","Saturday","土曜日","どようび","doyōbi","星期六","xīngqīliù"],
        ["semana","week","週","しゅう","shū","星期","xīngqī"],
        ["fim de semana","weekend","週末","しゅうまつ","shūmatsu","周末","zhōumò"],
        ["dinheiro","money","お金","おかね","okane","钱","qián"],
      ] },
      { titulo: "Transporte", itens: [
        ["ônibus","bus","バス","バス","basu","公交车","gōngjiāochē"],
        ["trem","train","電車","でんしゃ","densha","火车","huǒchē"],
        ["andar (a pé)","walk","歩く","あるく","aruku","走","zǒu"],
        ["correr","run","走る","はしる","hashiru","跑","pǎo"],
        ["avião","airplane","飛行機","ひこうき","hikōki","飞机","fēijī"],
      ] },
    ]
  },
  {
    nivel: "Intermediário",
    descricao: "Pronomes, perguntas, corpo, sentimentos e os verbos e adjetivos que você mais vai usar.",
    unidades: [
      { titulo: "Pronomes", itens: [
        ["eu","I","私","わたし","watashi","我","wǒ"],
        ["você","you","あなた","あなた","anata","你","nǐ"],
        ["ele","he","彼","かれ","kare","他","tā"],
        ["ela","she","彼女","かのじょ","kanojo","她","tā"],
        ["nós","we","私たち","わたしたち","watashitachi","我们","wǒmen"],
      ] },
      { titulo: "Perguntas", itens: [
        ["o quê","what","何","なに","nani","什么","shénme"],
        ["quem","who","誰","だれ","dare","谁","shéi"],
        ["onde","where","どこ","どこ","doko","哪里","nǎlǐ"],
        ["quando","when","いつ","いつ","itsu","什么时候","shénme shíhou"],
        ["por quê","why","なぜ","なぜ","naze","为什么","wèishénme"],
      ] },
      { titulo: "Corpo", itens: [
        ["cabeça","head","頭","あたま","atama","头","tóu"],
        ["olho","eye","目","め","me","眼睛","yǎnjing"],
        ["boca","mouth","口","くち","kuchi","嘴","zuǐ"],
        ["mão","hand","手","て","te","手","shǒu"],
        ["pé","foot","足","あし","ashi","脚","jiǎo"],
      ] },
      { titulo: "Sentimentos", itens: [
        ["feliz","happy","嬉しい","うれしい","ureshii","高兴","gāoxìng"],
        ["triste","sad","悲しい","かなしい","kanashii","难过","nánguò"],
        ["cansado","tired","疲れた","つかれた","tsukareta","累","lèi"],
        ["gostar","like","好き","すき","suki","喜欢","xǐhuan"],
        ["amar","love","愛する","あいする","aisuru","爱","ài"],
      ] },
      { titulo: "Comunicar", itens: [
        ["ler","read","読む","よむ","yomu","读","dú"],
        ["escrever","write","書く","かく","kaku","写","xiě"],
        ["ouvir","listen","聞く","きく","kiku","听","tīng"],
        ["falar","speak","話す","はなす","hanasu","说话","shuōhuà"],
        ["comprar","buy","買う","かう","kau","买","mǎi"],
      ] },
      { titulo: "Rotina", itens: [
        ["dormir","sleep","寝る","ねる","neru","睡觉","shuìjiào"],
        ["trabalhar","work","働く","はたらく","hataraku","工作","gōngzuò"],
        ["estudar","study","勉強する","べんきょうする","benkyō suru","学习","xuéxí"],
        ["esperar","wait","待つ","まつ","matsu","等","děng"],
        ["abrir","open","開ける","あける","akeru","开","kāi"],
      ] },
      { titulo: "Descrever coisas II", itens: [
        ["quente (clima)","hot","暑い","あつい","atsui","热","rè"],
        ["frio (clima)","cold","寒い","さむい","samui","冷","lěng"],
        ["caro","expensive","高い","たかい","takai","贵","guì"],
        ["barato","cheap","安い","やすい","yasui","便宜","piányi"],
        ["difícil","difficult","難しい","むずかしい","muzukashii","难","nán"],
      ] },
      { titulo: "Na cidade", itens: [
        ["hospital","hospital","病院","びょういん","byōin","医院","yīyuàn"],
        ["restaurante","restaurant","レストラン","レストラン","resutoran","餐厅","cāntīng"],
        ["banheiro","restroom","トイレ","トイレ","toire","厕所","cèsuǒ"],
        ["rua, caminho","street, road","道","みち","michi","路","lù"],
        ["hotel","hotel","ホテル","ホテル","hoteru","酒店","jiǔdiàn"],
      ] },
    ]
  },
  {
    nivel: "Avançado",
    descricao: "Frases inteiras: apresentar-se, pedir comida, pedir direção, contar a rotina, conversar e fazer planos.",
    unidades: [
      { titulo: "Apresentar-se", itens: [
        ["Muito prazer.","Nice to meet you.","はじめまして。","はじめまして。","hajimemashite","很高兴认识你。","hěn gāoxìng rènshi nǐ"],
        ["Meu nome é Ana.","My name is Ana.","私はアナです。","わたしはアナです。","watashi wa Ana desu","我叫安娜。","wǒ jiào Ānnà"],
        ["Eu sou do Brasil.","I'm from Brazil.","ブラジルから来ました。","ブラジルからきました。","Burajiru kara kimashita","我来自巴西。","wǒ láizì Bāxī"],
        ["Eu sou estudante.","I'm a student.","私は学生です。","わたしはがくせいです。","watashi wa gakusei desu","我是学生。","wǒ shì xuésheng"],
        ["Como vai você?","How are you?","お元気ですか。","おげんきですか。","ogenki desu ka","你好吗？","nǐ hǎo ma"],
      ] },
      { titulo: "No restaurante", itens: [
        ["Quanto custa?","How much is it?","いくらですか。","いくらですか。","ikura desu ka","多少钱？","duōshao qián"],
        ["Água, por favor.","Water, please.","水をください。","みずをください。","mizu o kudasai","请给我水。","qǐng gěi wǒ shuǐ"],
        ["Eu quero este.","I'd like this one.","これをください。","これをください。","kore o kudasai","我要这个。","wǒ yào zhège"],
        ["Está delicioso.","It's delicious.","おいしいです。","おいしいです。","oishii desu","很好吃。","hěn hǎochī"],
        ["A conta, por favor.","The check, please.","お会計をお願いします。","おかいけいをおねがいします。","okaikei o onegai shimasu","买单。","mǎidān"],
      ] },
      { titulo: "Pedir direção", itens: [
        ["Onde fica a estação?","Where is the station?","駅はどこですか。","えきはどこですか。","eki wa doko desu ka","车站在哪里？","chēzhàn zài nǎlǐ"],
        ["Onde fica o banheiro?","Where is the restroom?","トイレはどこですか。","トイレはどこですか。","toire wa doko desu ka","厕所在哪里？","cèsuǒ zài nǎlǐ"],
        ["Siga em frente.","Go straight ahead.","まっすぐ行ってください。","まっすぐいってください。","massugu itte kudasai","一直往前走。","yìzhí wǎng qián zǒu"],
        ["Vire à direita.","Turn right.","右に曲がってください。","みぎにまがってください。","migi ni magatte kudasai","往右转。","wǎng yòu zhuǎn"],
        ["É longe?","Is it far?","遠いですか。","とおいですか。","tōi desu ka","远吗？","yuǎn ma"],
      ] },
      { titulo: "Contar a rotina", itens: [
        ["Eu acordo às sete.","I wake up at seven.","七時に起きます。","しちじにおきます。","shichiji ni okimasu","我七点起床。","wǒ qī diǎn qǐchuáng"],
        ["Eu tomo café da manhã.","I eat breakfast.","朝ご飯を食べます。","あさごはんをたべます。","asagohan o tabemasu","我吃早饭。","wǒ chī zǎofàn"],
        ["Vou para a empresa de trem.","I go to the office by train.","電車で会社に行きます。","でんしゃでかいしゃにいきます。","densha de kaisha ni ikimasu","我坐火车去公司。","wǒ zuò huǒchē qù gōngsī"],
        ["Ontem eu estudei.","I studied yesterday.","昨日勉強しました。","きのうべんきょうしました。","kinō benkyō shimashita","我昨天学习了。","wǒ zuótiān xuéxí le"],
        ["Amanhã eu vou descansar.","I will rest tomorrow.","明日は休みます。","あしたはやすみます。","ashita wa yasumimasu","明天我休息。","míngtiān wǒ xiūxi"],
      ] },
      { titulo: "Conversar", itens: [
        ["Eu não entendo.","I don't understand.","わかりません。","わかりません。","wakarimasen","我不明白。","wǒ bù míngbai"],
        ["Pode falar mais devagar?","Could you speak more slowly?","もっとゆっくり話してください。","もっとゆっくりはなしてください。","motto yukkuri hanashite kudasai","请说慢一点。","qǐng shuō màn yìdiǎn"],
        ["O que isso significa?","What does this mean?","これはどういう意味ですか。","これはどういういみですか。","kore wa dō iu imi desu ka","这是什么意思？","zhè shì shénme yìsi"],
        ["Eu acho que sim.","I think so.","そう思います。","そうおもいます。","sō omoimasu","我觉得是。","wǒ juéde shì"],
        ["Eu gosto de aprender línguas.","I like learning languages.","言葉を勉強するのが好きです。","ことばをべんきょうするのがすきです。","kotoba o benkyō suru no ga suki desu","我喜欢学语言。","wǒ xǐhuan xué yǔyán"],
      ] },
      { titulo: "Planos e experiências", itens: [
        ["Eu quero viajar para o Japão.","I want to travel to Japan.","日本に旅行したいです。","にほんにりょこうしたいです。","Nihon ni ryokō shitai desu","我想去日本旅行。","wǒ xiǎng qù Rìběn lǚxíng"],
        ["Eu já fui à China.","I have been to China.","中国に行ったことがあります。","ちゅうごくにいったことがあります。","Chūgoku ni itta koto ga arimasu","我去过中国。","wǒ qùguo Zhōngguó"],
        ["Se chover, eu fico em casa.","If it rains, I'll stay home.","雨が降ったら、家にいます。","あめがふったら、いえにいます。","ame ga futtara, ie ni imasu","如果下雨，我就待在家。","rúguǒ xià yǔ, wǒ jiù dāi zài jiā"],
        ["Estudo chinês há um ano.","I have been studying Chinese for a year.","一年間中国語を勉強しています。","いちねんかんちゅうごくごをべんきょうしています。","ichinenkan chūgokugo o benkyō shite imasu","我学中文学了一年了。","wǒ xué Zhōngwén xuéle yì nián le"],
        ["Quanto mais pratico, melhor fico.","The more I practice, the better I get.","練習すればするほど上手になります。","れんしゅうすればするほどじょうずになります。","renshū sureba suru hodo jōzu ni narimasu","我越练习越好。","wǒ yuè liànxí yuè hǎo"],
      ] },
    ]
  }
];
