// Aulas de gramática — japonês. Formato descrito em gram-en.js.
// Exemplos: [frase em japonês, leitura (kana · romaji), tradução]
window.GRAMATICA = window.GRAMATICA || {};
window.GRAMATICA.jp = {
  fund: [
    {
      titulo: "As três escritas do japonês",
      objetivo: "Entender para que servem hiragana, katakana e kanji e como elas se misturam numa frase.",
      secoes: [
        { t: "Uma frase, três escritas", texto: "Uma frase japonesa normal mistura as três escritas. Veja: 私はコーヒーが好きです (eu gosto de café).\n• 私, 好 → kanji: carregam o significado (substantivos, raiz dos verbos e adjetivos)\n• コーヒー → katakana: palavras estrangeiras\n• は, が, きです → hiragana: gramática (partículas e terminações)",
          exemplos: [["私はコーヒーが好きです。", "わたしはコーヒーがすきです · watashi wa kōhī ga suki desu", "Eu gosto de café."]] },
        { t: "Hiragana: comece por aqui", texto: "São 46 símbolos básicos. Cada um é uma sílaba e tem SEMPRE o mesmo som. Com o hiragana você já consegue escrever qualquer palavra japonesa, mesmo sem saber o kanji. Livros infantis são só em hiragana.",
          tabela: [["", "a", "i", "u", "e", "o"], ["—", "あ", "い", "う", "え", "お"], ["k", "か", "き", "く", "け", "こ"], ["s", "さ", "し (shi)", "す", "せ", "そ"], ["t", "た", "ち (chi)", "つ (tsu)", "て", "と"], ["n", "な", "に", "ぬ", "ね", "の"]] },
        { t: "Katakana: mesmos sons, outro visual", texto: "Mesmos sons do hiragana, com traços retos. Serve para palavras estrangeiras, nomes de fora e ênfase (como o itálico). O traço ー alonga a vogal.",
          exemplos: [["ブラジル", "Burajiru", "Brasil"], ["コーヒー", "kōhī", "café"], ["パン", "pan", "pão (do português!)"]] },
        { t: "Kanji: aos poucos", texto: "Os kanji vieram da China. Cada um tem significado e normalmente mais de uma leitura. Não tente decorar sozinhos: aprenda-os dentro das palavras, como neste curso. Com uns 300 você já lê muita coisa do dia a dia.",
          exemplos: [["山", "やま · yama", "montanha"], ["日本", "にほん · nihon", "Japão (origem do sol)"]] },
      ],
      erros: ["Tentar aprender kanji antes do hiragana.", "Ler し como \"si\" e ち como \"ti\": são shi e chi.", "Achar que o katakana tem sons diferentes: é o mesmo silabário."],
      pratica: [
        { p: "Em 私はブラジル人です, quais partes são katakana?", r: "ブラジル (Brasil)." },
        { p: "Como se lê つ?", r: "tsu." },
        { p: "Para que serve o traço ー em コーヒー?", r: "Alonga a vogal anterior: ko-o-hi-i." },
      ],
    },
    {
      titulo: "Sons especiais: ゛, ゜, sons compostos e っ",
      objetivo: "Ler qualquer palavra em kana, incluindo sons sonoros, sílabas compostas e consoantes dobradas.",
      secoes: [
        { t: "゛ (dakuten) e ゜ (handakuten)", texto: "Os dois tracinhos deixam o som \"sonoro\": k→g, s→z, t→d, h→b. A bolinha transforma h em p.",
          tabela: [["Base", "Com ゛", "Com ゜"], ["か ka", "が ga", "—"], ["さ sa", "ざ za", "—"], ["た ta", "だ da", "—"], ["は ha", "ば ba", "ぱ pa"]] },
        { t: "Sílabas compostas (ゃ ゅ ょ pequenos)", texto: "Uma sílaba com i + ya/yu/yo pequeno vira um som só. Repare no tamanho: きや (ki-ya, duas sílabas) × きゃ (kya, uma sílaba).",
          exemplos: [["きゃく", "kyaku", "cliente"], ["しゃしん", "shashin", "foto"], ["りょこう", "ryokō", "viagem"]] },
        { t: "っ pequeno: a pausa", texto: "Um つ pequeno dobra a consoante seguinte. Na fala é uma pausa curta, como se a língua travasse um instante. Muda o sentido!",
          exemplos: [["きて", "kite", "venha"], ["きって", "kitte", "selo"], ["がっこう", "gakkō", "escola"]] },
        { t: "Vogais longas", texto: "No hiragana, a vogal longa é escrita com uma vogal extra: おかあさん (okāsan), おおきい (ōkii), とうきょう (Tōkyō). O ou e o ei costumam soar como o e e longos. A duração muda o sentido: おばさん (tia) × おばあさん (avó).",
          exemplos: [["おばさん", "obasan", "tia"], ["おばあさん", "obāsan", "avó"]] },
      ],
      erros: ["Não fazer a pausa do っ: きって vira きて.", "Encurtar vogais longas: ビル (prédio) × ビール (cerveja).", "Ler きゃ como duas sílabas."],
      pratica: [
        { p: "Leia: ざっし", r: "zasshi (revista)." },
        { p: "Qual a diferença entre びょういん e びよういん?", r: "byōin = hospital; biyōin = salão de beleza. O ょ pequeno muda tudo." },
      ],
    },
  ],
  a1: [
    {
      titulo: "A frase básica: X は Y です",
      objetivo: "Dizer o que algo ou alguém é, negar e perguntar.",
      secoes: [
        { t: "A estrutura", texto: "X は Y です = \"quanto a X, é Y\". は marca o TÓPICO (do que estamos falando) e, como partícula, se lê \"wa\". です no fim é o \"é\" educado. Não há artigo nem conjugação por pessoa.",
          exemplos: [["私は学生です。", "わたしはがくせいです · watashi wa gakusei desu", "Eu sou estudante."], ["これは本です。", "これはほんです · kore wa hon desu", "Isto é um livro."]] },
        { t: "Pergunta: só acrescente か", texto: "Não muda a ordem nem a entonação obrigatoriamente: か no fim já é o ponto de interrogação falado.",
          exemplos: [["学生ですか。", "がくせいですか · gakusei desu ka", "Você é estudante?"], ["はい、そうです。", "hai, sō desu", "Sim, sou."]] },
        { t: "Negativa", texto: "です → じゃありません (fala) ou ではありません (mais formal). Passado: でした (era), じゃありませんでした (não era).",
          tabela: [["", "Afirmativo", "Negativo"], ["Presente", "学生です", "学生じゃありません"], ["Passado", "学生でした", "学生じゃありませんでした"]] },
        { t: "O sujeito some", texto: "Se está claro de quem se fala, o japonês omite. \"学生です\" sozinho já é \"sou estudante\". Repetir 私は o tempo todo soa estranho.",
          exemplos: [["ブラジル人です。", "ブラジルじんです · burajiru-jin desu", "Sou brasileiro."]] },
        { t: "も: também", texto: "も substitui は quando o tópico repete a informação anterior.",
          exemplos: [["私も学生です。", "わたしもがくせいです · watashi mo gakusei desu", "Eu também sou estudante."]] },
      ],
      erros: ["Ler a partícula は como \"ha\": é \"wa\".", "Dizer 私は em toda frase.", "Usar です com verbo: \"食べるです\" não existe."],
      pratica: [
        { p: "Traduza: \"Isto é um telefone?\"", r: "これは電話ですか。(kore wa denwa desu ka)" },
        { p: "Negue: 先生です。", r: "先生じゃありません。(sensei ja arimasen)" },
        { p: "Como dizer \"Ele também é japonês\"?", r: "彼も日本人です。(kare mo nihon-jin desu)" },
      ],
    },
    {
      titulo: "Partículas: の, を, に, で",
      objetivo: "Entender as \"etiquetas\" que dizem o papel de cada palavra na frase.",
      secoes: [
        { t: "Por que partículas", texto: "Em português, a ordem das palavras diz quem faz o quê. Em japonês, quem diz isso é a partícula que vem DEPOIS de cada palavra. Por isso a ordem é mais flexível, desde que o verbo fique no fim.",
          tabela: [["Partícula", "Função", "Como pensar"], ["は (wa)", "tópico", "quanto a…"], ["の", "posse, ligação", "de"], ["を (o)", "objeto direto", "o quê?"], ["に", "destino, horário, alvo", "para, em, às"], ["で", "lugar da ação, meio", "em, com, de (trem)"]] },
        { t: "の: de", texto: "A の B = B de A. A ordem é a inversa do português: 私の本 = \"eu-de livro\" = meu livro.",
          exemplos: [["私の本", "わたしのほん · watashi no hon", "meu livro"], ["日本の車", "にほんのくるま · nihon no kuruma", "carro do Japão"]] },
        { t: "を: o objeto", texto: "Marca o que sofre a ação. Escreve-se を e lê-se \"o\".",
          exemplos: [["お茶を飲みます。", "おちゃをのみます · ocha o nomimasu", "Bebo chá."]] },
        { t: "に e で", texto: "に = destino (ir PARA), horário exato (ÀS 7) e onde algo EXISTE. で = onde a ação ACONTECE e o meio (DE trem, COM hashi).",
          exemplos: [["学校に行きます。", "がっこうにいきます · gakkō ni ikimasu", "Vou para a escola."], ["七時に起きます。", "しちじにおきます · shichiji ni okimasu", "Acordo às sete."], ["会社で働きます。", "かいしゃではたらきます · kaisha de hatarakimasu", "Trabalho na empresa."], ["電車で行きます。", "でんしゃでいきます · densha de ikimasu", "Vou de trem."]] },
      ],
      erros: ["Trocar に por で: 会社に働きます está errado (trabalhar é ação → で).", "Esquecer を: お茶飲みます é aceito na fala, mas aprenda com を.", "Inverter の: 本の私 = \"eu do livro\"."],
      pratica: [
        { p: "に ou で? 図書館 ___ 勉強します (estudo na biblioteca).", r: "で (lugar onde a ação acontece)." },
        { p: "に ou で? 日本 ___ 行きます (vou ao Japão).", r: "に (destino)." },
        { p: "Traduza: \"o carro do meu pai\"", r: "父の車 (chichi no kuruma)." },
      ],
    },
    {
      titulo: "Verbos na forma ます",
      objetivo: "Conjugar qualquer verbo no presente, passado, negativo e fazer convites.",
      secoes: [
        { t: "Ordem: o verbo sempre no fim", texto: "Sujeito – (objeto) – verbo. A forma ます é a educada, perfeita para quem está começando: serve com qualquer pessoa.",
          exemplos: [["私はパンを食べます。", "わたしはパンをたべます · watashi wa pan o tabemasu", "Eu como pão."]] },
        { t: "As 4 formas", texto: "Troque só a terminação. O japonês não conjuga por pessoa (eu, você, ele: tudo igual) e ます vale para presente E futuro.",
          tabela: [["", "Afirmativo", "Negativo"], ["Presente/futuro", "食べます (como)", "食べません (não como)"], ["Passado", "食べました (comi)", "食べませんでした (não comi)"]] },
        { t: "Convites", texto: "〜ませんか = \"não quer…?\" (convite educado). 〜ましょう = \"vamos…!\"",
          exemplos: [["一緒に行きませんか。", "いっしょにいきませんか · issho ni ikimasen ka", "Não quer ir junto?"], ["行きましょう。", "いきましょう · ikimashō", "Vamos!"]] },
        { t: "Verbos para começar", texto: "行きます (ir), 来ます (vir), 帰ります (voltar para casa), 食べます (comer), 飲みます (beber), 見ます (ver), 買います (comprar), します (fazer), 起きます (acordar), 寝ます (dormir)." },
      ],
      erros: ["Achar que precisa de palavra para futuro: 明日行きます já é \"vou amanhã\".", "Conjugar por pessoa: não existe \"eu como / ele come\" diferente."],
      pratica: [
        { p: "Passado negativo de 飲みます", r: "飲みませんでした (não bebi)." },
        { p: "Convide: \"Não quer comer sushi?\"", r: "寿司を食べませんか。(sushi o tabemasen ka)" },
      ],
    },
    {
      titulo: "Adjetivos い e な",
      objetivo: "Descrever coisas e conjugar os dois tipos de adjetivo.",
      secoes: [
        { t: "Dois tipos", texto: "Adjetivos い terminam em い e se conjugam sozinhos: 大きい, 高い, 新しい. Adjetivos な funcionam como substantivos e levam な antes de outro substantivo: きれい, 静か, 好き.",
          exemplos: [["大きい車", "おおきいくるま · ōkii kuruma", "carro grande"], ["きれいな花", "きれいなはな · kirei na hana", "flor bonita"]] },
        { t: "Conjugação", texto: "い: troque o い final. な: use です / じゃありません como um substantivo.",
          tabela: [["", "い (高い)", "な (静か)"], ["é", "高いです", "静かです"], ["não é", "高くないです", "静かじゃありません"], ["foi", "高かったです", "静かでした"], ["não foi", "高くなかったです", "静かじゃありませんでした"]] },
        { t: "A exceção いい", texto: "いい (bom) se conjuga a partir de よい: よくない (não é bom), よかった (foi bom).",
          exemplos: [["よかったです。", "yokatta desu", "Foi bom / que bom."]] },
        { t: "Ligar adjetivos: て", texto: "い → くて; な → で. Assim você diz \"barato e gostoso\".",
          exemplos: [["安くておいしい。", "やすくておいしい · yasukute oishii", "Barato e gostoso."], ["きれいで静か。", "kirei de shizuka", "Bonito e tranquilo."]] },
      ],
      erros: ["\"高いでした\" → 高かったです.", "\"きれいくない\" → きれいじゃありません (きれい é な, apesar do い no fim).", "\"いくない\" → よくない."],
      pratica: [
        { p: "Negue: おいしいです", r: "おいしくないです。" },
        { p: "Passado de 簡単です (fácil)", r: "簡単でした。" },
        { p: "Diga \"quarto grande e limpo\"", r: "大きくてきれいな部屋 (ōkikute kirei na heya)." },
      ],
    },
  ],
  a2: [
    {
      titulo: "Os grupos de verbos e a forma de dicionário",
      objetivo: "Reconhecer os 3 grupos de verbos: a base para todas as outras formas.",
      secoes: [
        { t: "Por que isso importa", texto: "Até aqui você usou ます. Mas os japoneses falam entre amigos com a forma de dicionário (食べる, 行く), e quase toda gramática nova (querer, poder, experiência, condicional) parte dela. Tudo depende de saber o grupo do verbo." },
        { t: "Os três grupos", texto: "Grupo 1 (godan): terminam em -u, com a sílaba antes do ます em -i: 行きます → 行く, 飲みます → 飲む, 買います → 買う.\nGrupo 2 (ichidan): terminam em -eru ou -iru e perdem só ます → る: 食べます → 食べる, 見ます → 見る.\nGrupo 3 (irregulares): só dois! します → する, 来ます → 来る (kuru).",
          tabela: [["Grupo", "ます", "Dicionário"], ["1", "書きます", "書く"], ["1", "話します", "話す"], ["1", "待ちます", "待つ"], ["2", "起きます", "起きる"], ["3", "します", "する"], ["3", "来ます", "来る"]] },
        { t: "Armadilha", texto: "Alguns verbos terminados em -eru/-iru são do grupo 1: 帰る (voltar), 入る (entrar), 走る (correr), 知る (saber). Na forma ます eles entregam o grupo: 帰ります (kaeri-masu, com i → grupo 1)." },
      ],
      erros: ["Achar que todo verbo em -ru é grupo 2.", "Dizer 来る como \"kiru\": é kuru (e kimasu na forma ます)."],
      pratica: [
        { p: "Forma de dicionário de 飲みます", r: "飲む (nomu)." },
        { p: "Grupo de 見る?", r: "Grupo 2 (見ます → 見る)." },
        { p: "Forma de dicionário de 帰ります", r: "帰る (kaeru) — grupo 1." },
      ],
    },
    {
      titulo: "A forma て: a mais importante do japonês",
      objetivo: "Formar a forma て e usá-la para pedir, ligar ações e dizer o que está acontecendo.",
      secoes: [
        { t: "Como formar", texto: "Grupo 2: troque る por て (食べる → 食べて). Grupo 3: して, 来て. Grupo 1 depende da última sílaba: decore a \"música\" abaixo.",
          tabela: [["Termina em", "Vira", "Exemplo"], ["う, つ, る", "って", "買う → 買って, 待つ → 待って"], ["む, ぶ, ぬ", "んで", "飲む → 飲んで"], ["く", "いて", "書く → 書いて"], ["ぐ", "いで", "泳ぐ → 泳いで"], ["す", "して", "話す → 話して"], ["exceção", "行く → 行って", ""]] },
        { t: "Uso 1: pedir (〜てください)", texto: "Forma て + ください = \"por favor, faça\".",
          exemplos: [["待ってください。", "まってください · matte kudasai", "Espere, por favor."], ["ゆっくり話してください。", "ゆっくりはなしてください · yukkuri hanashite kudasai", "Fale devagar, por favor."]] },
        { t: "Uso 2: estar fazendo (〜ています)", texto: "Forma て + います = ação em andamento ou estado resultante.",
          exemplos: [["今、勉強しています。", "いま、べんきょうしています · ima benkyō shite imasu", "Estou estudando agora."], ["東京に住んでいます。", "とうきょうにすんでいます · Tōkyō ni sunde imasu", "Moro em Tóquio."]] },
        { t: "Uso 3: ligar ações em sequência", texto: "\"Fiz A, e depois B\": só o último verbo mostra o tempo.",
          exemplos: [["起きて、朝ご飯を食べて、会社に行きました。", "おきて、あさごはんをたべて、かいしゃにいきました · okite, asagohan o tabete, kaisha ni ikimashita", "Acordei, tomei café e fui para a empresa."]] },
        { t: "Uso 4: permissão e proibição", texto: "〜てもいいですか = posso…? 〜てはいけません = não pode.",
          exemplos: [["写真を撮ってもいいですか。", "しゃしんをとってもいいですか · shashin o totte mo ii desu ka", "Posso tirar foto?"]] },
      ],
      erros: ["\"行いて\" → 行って (a única exceção do grupo 1).", "Usar ています para planos futuros: 明日行っています está errado; diga 明日行きます."],
      pratica: [
        { p: "Forma て de 読む", r: "読んで (yonde)." },
        { p: "Forma て de 書く", r: "書いて (kaite)." },
        { p: "Diga: \"O que você está fazendo?\"", r: "何をしていますか。(nani o shite imasu ka)" },
      ],
    },
    {
      titulo: "Querer, gostar e comparar",
      objetivo: "Expressar desejos e preferências e comparar coisas.",
      secoes: [
        { t: "〜たい: querer fazer", texto: "Tire o ます e ponha たい. たい se conjuga como adjetivo い.",
          exemplos: [["日本に行きたいです。", "にほんにいきたいです · Nihon ni ikitai desu", "Quero ir ao Japão."], ["行きたくないです。", "いきたくないです · ikitaku nai desu", "Não quero ir."]] },
        { t: "欲しい: querer uma coisa", texto: "O que se quer leva が.",
          exemplos: [["新しいスマホが欲しいです。", "あたらしいスマホがほしいです · atarashii sumaho ga hoshii desu", "Quero um celular novo."]] },
        { t: "好き・嫌い: gostar", texto: "Não são verbos, são adjetivos な. O que se gosta leva が. Para atividades, use verbo + の.",
          exemplos: [["音楽が好きです。", "おんがくがすきです · ongaku ga suki desu", "Gosto de música."], ["泳ぐのが好きです。", "およぐのがすきです · oyogu no ga suki desu", "Gosto de nadar."]] },
        { t: "Comparar", texto: "A は B より + adjetivo = A é mais … que B. Superlativo: 一番 (ichiban, número um). Pergunta de escolha: A と B と どちらが…?",
          exemplos: [["電車はバスより速いです。", "でんしゃはバスよりはやいです · densha wa basu yori hayai desu", "O trem é mais rápido que o ônibus."], ["何が一番好きですか。", "なにがいちばんすきですか · nani ga ichiban suki desu ka", "Do que você mais gosta?"]] },
      ],
      erros: ["\"音楽を好きです\" → 音楽が好きです.", "Usar 〜たい para outra pessoa: 彼は行きたいです soa estranho; diga 行きたがっています ou 行きたいそうです.", "Usar もっと para comparar com より: basta より."],
      pratica: [
        { p: "Diga: \"Quero beber água.\"", r: "水を飲みたいです。(mizu o nomitai desu)" },
        { p: "Diga: \"O Japão é menor que o Brasil.\"", r: "日本はブラジルより小さいです。" },
      ],
    },
    {
      titulo: "A forma simples (casual) e o passado た",
      objetivo: "Falar com amigos e entender a forma que aparece dentro de frases maiores.",
      secoes: [
        { t: "Educado × casual", texto: "Com amigos e família, o japonês usa a forma simples. Ela também é obrigatória dentro de frases maiores (\"acho que…\", \"o livro que comprei…\"), mesmo em conversa educada.",
          tabela: [["Educado", "Casual", "Sentido"], ["食べます", "食べる", "como"], ["食べません", "食べない", "não como"], ["食べました", "食べた", "comi"], ["食べませんでした", "食べなかった", "não comi"], ["学生です", "学生だ", "é estudante"]] },
        { t: "Como fazer o た", texto: "É igual à forma て, trocando て por た e で por だ: 食べて → 食べた, 飲んで → 飲んだ, 行って → 行った.",
          exemplos: [["昨日、映画を見た。", "きのう、えいがをみた · kinō, eiga o mita", "Ontem vi um filme."]] },
        { t: "Negativo ない", texto: "Grupo 2: る → ない (食べない). Grupo 1: troque o som u por a + ない (行く → 行かない, 飲む → 飲まない; う vira わ: 買う → 買わない). Irregulares: しない, 来ない (konai). ある vira ない.",
          exemplos: [["わからない。", "wakaranai", "Não sei / não entendo."]] },
      ],
      erros: ["Usar forma casual com chefe ou desconhecido.", "\"あらない\" → o negativo de ある é ない.", "\"買あない\" → 買わない."],
      pratica: [
        { p: "Forma casual de 行きませんでした", r: "行かなかった (ikanakatta)." },
        { p: "Forma casual de 飲みました", r: "飲んだ (nonda)." },
      ],
    },
  ],
  b1: [
    {
      titulo: "Dar motivos e opinião: から, ので, と思う",
      objetivo: "Explicar por quê e dizer o que você acha.",
      secoes: [
        { t: "から e ので", texto: "Os dois significam \"porque\" e vêm DEPOIS do motivo. から é mais direto e subjetivo; ので soa mais suave e objetivo, ideal para pedidos e desculpas. Antes deles, use a forma simples (com substantivo e adjetivo な: だから, なので).",
          exemplos: [["雨だから、行きません。", "あめだから、いきません · ame da kara, ikimasen", "Como está chovendo, não vou."], ["電車が遅れたので、遅くなりました。", "でんしゃがおくれたので、おそくなりました · densha ga okureta node, osoku narimashita", "Como o trem atrasou, eu me atrasei."]] },
        { t: "と思います", texto: "Forma simples + と思います = \"acho que…\". É a estrutura de opinião mais usada, e também deixa afirmações mais suaves.",
          exemplos: [["明日は雨が降ると思います。", "あしたはあめがふるとおもいます · ashita wa ame ga furu to omoimasu", "Acho que amanhã vai chover."], ["彼は来ないと思います。", "かれはこないとおもいます · kare wa konai to omoimasu", "Acho que ele não vem."]] },
        { t: "Intenção: forma volitiva + と思っています", texto: "Volitiva: grupo 2 る → よう (食べよう); grupo 1 u → ō (行こう, 飲もう); しよう, 来よう. + と思っています = \"estou pensando em…\".",
          exemplos: [["日本語を勉強しようと思っています。", "にほんごをべんきょうしようとおもっています · nihongo o benkyō shiyō to omotte imasu", "Estou pensando em estudar japonês."]] },
      ],
      erros: ["\"雨からです\" → 雨だから / 雨なので.", "Colocar o motivo depois: から sempre vem logo após a causa.", "\"行くと思いません\" é possível, mas o natural é 行かないと思います (negar dentro)."],
      pratica: [
        { p: "Diga: \"Como estou cansado, vou dormir.\"", r: "疲れたので、寝ます。(tsukareta node, nemasu)" },
        { p: "Diga: \"Acho que é caro.\"", r: "高いと思います。(takai to omoimasu)" },
      ],
    },
    {
      titulo: "Condicionais: たら, ば, と",
      objetivo: "Falar de \"se\" e \"quando\" com a forma certa.",
      secoes: [
        { t: "たら: o coringa", texto: "Passado casual + ら. Serve para \"se\" e \"quando (depois que)\". Se estiver em dúvida, use たら.",
          exemplos: [["雨が降ったら、家にいます。", "あめがふったら、いえにいます · ame ga futtara, ie ni imasu", "Se chover, fico em casa."], ["着いたら、電話してください。", "ついたら、でんわしてください · tsuitara, denwa shite kudasai", "Quando chegar, me ligue."]] },
        { t: "と: consequência automática", texto: "Forma de dicionário + と = sempre que A, B (fatos, instruções, máquinas). Não serve para pedidos nem vontades.",
          exemplos: [["このボタンを押すと、ドアが開きます。", "このボタンをおすと、ドアがあきます · kono botan o osu to, doa ga akimasu", "Apertando este botão, a porta abre."]] },
        { t: "ば: condição necessária", texto: "Grupo 1: u → e + ば (行けば). Grupo 2: る → れば (食べれば). い-adj: い → ければ (安ければ). Destaca a condição, e aparece em conselhos: 〜ばいい = \"é só…\".",
          exemplos: [["安ければ、買います。", "やすければ、かいます · yasukereba, kaimasu", "Se for barato, compro."], ["どうすればいいですか。", "dō sureba ii desu ka", "O que eu faço? (como seria bom fazer?)"]] },
      ],
      erros: ["Usar と com pedido: 着くと電話してください está errado → 着いたら.", "\"安いたら\" → 安かったら."],
      pratica: [
        { p: "Diga com たら: \"Se tiver tempo, vou.\"", r: "時間があったら、行きます。" },
        { p: "Forma ば de 食べる", r: "食べれば (tabereba)." },
      ],
    },
    {
      titulo: "Frases que descrevem substantivos",
      objetivo: "Dizer \"o livro que comprei\", \"a pessoa que mora ali\" sem pronome relativo.",
      secoes: [
        { t: "O segredo: a frase vem antes", texto: "O japonês não tem \"que\". A frase descritiva inteira, na forma simples, vem ANTES do substantivo, como se fosse um adjetivo gigante.",
          exemplos: [["昨日買った本", "きのうかったほん · kinō katta hon", "o livro que comprei ontem"], ["あそこに住んでいる人", "あそこにすんでいるひと · asoko ni sunde iru hito", "a pessoa que mora ali"]] },
        { t: "Dentro da frase: が em vez de は", texto: "O sujeito da frase descritiva usa が (ou の), nunca は.",
          exemplos: [["私が作った料理", "わたしがつくったりょうり · watashi ga tsukutta ryōri", "a comida que eu fiz"]] },
        { t: "Montando frases longas", texto: "Construa de dentro para fora: [descrição] + substantivo, e use o conjunto como qualquer substantivo.",
          exemplos: [["私が昨日見た映画はとても面白かったです。", "わたしがきのうみたえいがはとてもおもしろかったです · watashi ga kinō mita eiga wa totemo omoshirokatta desu", "O filme que vi ontem foi muito interessante."]] },
      ],
      erros: ["Usar ます dentro: 買いました本 → 買った本.", "Usar は dentro: 私は作った料理 → 私が作った料理.", "Colocar a descrição depois do substantivo, como em português."],
      pratica: [
        { p: "Diga: \"o restaurante onde comemos\"", r: "私たちが食べたレストラン (watashitachi ga tabeta resutoran)." },
        { p: "Diga: \"a pessoa que usa óculos\"", r: "眼鏡をかけている人 (megane o kakete iru hito)." },
      ],
    },
  ],
  b2: [
    {
      titulo: "Passiva e causativa",
      objetivo: "Dizer o que aconteceu com você e o que você fez alguém fazer.",
      secoes: [
        { t: "Passiva: 〜られる", texto: "Grupo 2: る → られる (食べられる). Grupo 1: u → a + れる (読む → 読まれる, 言う → 言われる). する → される, 来る → 来られる. Quem fez leva に.",
          exemplos: [["先生に褒められました。", "せんせいにほめられました · sensei ni homeraremashita", "Fui elogiado pelo professor."], ["この本は世界中で読まれています。", "このほんはせかいじゅうでよまれています · kono hon wa sekaijū de yomarete imasu", "Este livro é lido no mundo todo."]] },
        { t: "Passiva de incômodo", texto: "Algo único do japonês: mesmo verbos sem objeto viram passiva para dizer que algo ATRAPALHOU você.",
          exemplos: [["雨に降られました。", "あめにふられました · ame ni furaremashita", "Peguei chuva (a chuva caiu em mim)."], ["財布を盗まれました。", "さいふをぬすまれました · saifu o nusumaremashita", "Roubaram minha carteira."]] },
        { t: "Causativa: 〜させる", texto: "Fazer/deixar alguém fazer. Grupo 2: る → させる. Grupo 1: u → a + せる (行く → 行かせる). する → させる, 来る → 来させる. 〜させてください = \"deixe-me fazer\" (muito educado).",
          exemplos: [["子供に野菜を食べさせます。", "こどもにやさいをたべさせます · kodomo ni yasai o tabesasemasu", "Faço a criança comer verduras."], ["少し考えさせてください。", "すこしかんがえさせてください · sukoshi kangaesasete kudasai", "Deixe-me pensar um pouco."]] },
      ],
      erros: ["Confundir 食べられる (potencial: consigo comer) com a passiva: a forma é igual no grupo 2; o contexto decide.", "Marcar quem fez com が na passiva: é に."],
      pratica: [
        { p: "Passiva de 言う", r: "言われる (iwareru)." },
        { p: "Diga educadamente: \"Deixe-me ajudar.\"", r: "手伝わせてください。(tetsudawasete kudasai)" },
      ],
    },
    {
      titulo: "Aparência e boato: そう, よう, らしい",
      objetivo: "Dizer \"parece\" e \"ouvi dizer\" com a nuance certa.",
      secoes: [
        { t: "〜そう (visual): parece, pela aparência", texto: "Raiz do verbo ou adjetivo sem い + そう. É o que você VÊ agora.",
          exemplos: [["おいしそうですね。", "oishisō desu ne", "Parece gostoso!"], ["雨が降りそうです。", "あめがふりそうです · ame ga furisō desu", "Parece que vai chover."]] },
        { t: "〜そうです (ouvi dizer)", texto: "Forma simples COMPLETA + そうです = relato de algo que ouviu. Repare: 降りそう (parece que vai) × 降るそう (dizem que vai).",
          exemplos: [["明日は雨が降るそうです。", "あしたはあめがふるそうです · ashita wa ame ga furu sō desu", "Dizem que amanhã vai chover."]] },
        { t: "〜ようです / みたい", texto: "Conclusão sua a partir de indícios (\"parece que\"). みたい é a versão falada.",
          exemplos: [["誰もいないようです。", "だれもいないようです · dare mo inai yō desu", "Parece que não tem ninguém."], ["風邪みたい。", "かぜみたい · kaze mitai", "Parece que é resfriado."]] },
        { t: "〜らしい", texto: "Informação indireta, meio distante (\"pelo que dizem\"). Também significa \"típico de\": 男らしい (másculo).",
          exemplos: [["彼は結婚したらしい。", "かれはけっこんしたらしい · kare wa kekkon shita rashii", "Parece que ele se casou."]] },
      ],
      erros: ["Trocar おいしそう (parece gostoso) por おいしいそう (dizem que é gostoso).", "いい + そう → よさそう (exceção)."],
      pratica: [
        { p: "Olhando um bolo: \"Parece gostoso!\"", r: "おいしそう！" },
        { p: "Diga: \"Dizem que ela é médica.\"", r: "彼女は医者だそうです。" },
      ],
    },
  ],
  c1: [
    {
      titulo: "Keigo: a linguagem respeitosa",
      objetivo: "Falar com clientes, chefes e desconhecidos no nível de educação esperado.",
      secoes: [
        { t: "Três níveis", texto: "丁寧語 (teineigo): o educado básico, です/ます, que você já usa.\n尊敬語 (sonkeigo): ELEVA a outra pessoa e as ações dela.\n謙譲語 (kenjōgo): REBAIXA você e as suas ações, para mostrar respeito.\nRegra de ouro: nunca use sonkeigo para você mesmo." },
        { t: "Verbos especiais", texto: "Os mais usados têm formas próprias. Decore esta tabela.",
          tabela: [["Normal", "尊敬語 (o outro)", "謙譲語 (eu)"], ["いる / 行く / 来る", "いらっしゃる", "おる / 参る"], ["言う", "おっしゃる", "申す"], ["食べる / 飲む", "召し上がる", "いただく"], ["する", "なさる", "いたす"], ["見る", "ご覧になる", "拝見する"], ["知っている", "ご存知だ", "存じている"]] },
        { t: "A fórmula geral", texto: "Para os outros verbos: お + raiz + になる (sonkeigo) e お + raiz + する (kenjōgo). Com palavras chinesas: ご + palavra.",
          exemplos: [["お待ちになりますか。", "おまちになりますか · omachi ni narimasu ka", "O senhor vai esperar?"], ["お持ちします。", "おもちします · omochi shimasu", "Eu levo para o senhor."], ["ご連絡いたします。", "ごれんらくいたします · gorenraku itashimasu", "Entrarei em contato."]] },
      ],
      erros: ["\"私がおっしゃいました\" → 私が申しました (keigo alto para si mesmo é erro grave).", "Misturar demais: 二重敬語 (keigo duplo) como おっしゃられる é considerado incorreto."],
      pratica: [
        { p: "Diga ao cliente: \"O senhor já comeu?\"", r: "もう召し上がりましたか。" },
        { p: "Diga humildemente: \"Eu vou verificar.\"", r: "確認いたします。" },
      ],
    },
    {
      titulo: "Nuance: わけ, こそ, さえ, のに",
      objetivo: "Expressar ênfase, justificativa e frustração como um nativo.",
      secoes: [
        { t: "わけ: faz sentido que", texto: "わけだ = \"então é por isso\"; わけではない = \"não é que…\"; わけがない = \"de jeito nenhum\".",
          exemplos: [["行きたくないわけじゃない。", "いきたくないわけじゃない · ikitaku nai wake ja nai", "Não é que eu não queira ir."], ["そんなわけがない。", "sonna wake ga nai", "Impossível!"]] },
        { t: "こそ e さえ", texto: "こそ destaca (\"justamente\"). さえ = \"até, nem mesmo\".",
          exemplos: [["こちらこそ。", "kochira koso", "Eu é que agradeço."], ["名前さえ知らない。", "なまえさえしらない · namae sae shiranai", "Nem sei o nome."]] },
        { t: "のに: frustração", texto: "\"Apesar de… (e não deveria ser assim)\". Carrega decepção ou pena.",
          exemplos: [["勉強したのに、落ちた。", "べんきょうしたのに、おちた · benkyō shita noni, ochita", "Estudei e mesmo assim reprovei."]] },
      ],
      erros: ["Usar のに para contraste neutro: prefira けど / が.", "Traduzir わけ sempre como \"motivo\": o sentido muda com a estrutura."],
      pratica: [
        { p: "Diga: \"Não é que eu não goste.\"", r: "嫌いなわけじゃない。" },
        { p: "Diga: \"Comprei, mas nunca usei (que pena).\"", r: "買ったのに、使っていない。" },
      ],
    },
  ],
};
