// Aulas de gramática — inglês. Formato:
// { titulo, objetivo, secoes: [{ t, texto, exemplos?: [[frase, leitura, tradução]], tabela?: [[...cabeçalho], [...linha]] }],
//   erros: ["…"], pratica: [{ p: pergunta, r: resposta }] }
window.GRAMATICA = window.GRAMATICA || {};
window.GRAMATICA.en = {
  fund: [
    {
      titulo: "Como o inglês soa (e por que não se lê como se escreve)",
      objetivo: "Entender os 4 hábitos do português que mais atrapalham a pronúncia em inglês e como corrigi-los.",
      secoes: [
        { t: "1. A escrita não é um guia confiável", texto: "Em português, quase sempre você lê exatamente o que está escrito. Em inglês, não. A mesma letra muda de som (o \"a\" de cat, cake e car são três sons diferentes) e várias letras não são pronunciadas (o k de knife, o w de write).\n\nPor isso a regra de ouro é: aprenda cada palavra pelo som primeiro. Toque no 🔊 antes de tentar ler.",
          exemplos: [["cat", "", "gato — a aberto, quase \"é\""], ["cake", "", "bolo — soa \"keik\""], ["car", "", "carro — a longo"], ["knife", "", "faca — o k é mudo"]] },
        { t: "2. Não acrescente vogal no fim", texto: "O português quase não termina palavras em consoante, então nosso ouvido coloca um \"i\" escondido: \"bigui\", \"doguí\", \"clubi\". Em inglês a palavra termina seca, na consoante. Treine segurando a boca parada no final.",
          exemplos: [["big", "", "grande — não \"bigui\""], ["dog", "", "cachorro — não \"dógui\""], ["club", "", "clube — não \"clubi\""]] },
        { t: "3. O TH existe e muda o sentido", texto: "Ponha a ponta da língua entre os dentes e sopre. Sem vibração é o TH de think; com vibração (como um d soprado) é o TH de this. Se você trocar por t, f ou d, pode virar outra palavra: three (três) × tree (árvore), think (pensar) × sink (pia).",
          exemplos: [["three / tree", "", "três / árvore"], ["think / sink", "", "pensar / pia"], ["this / dis", "", "isto / (prefixo)"]] },
        { t: "4. Sílaba forte e vogais fracas", texto: "Toda palavra inglesa tem uma sílaba forte, e as outras ficam fracas, quase engolidas, num som neutro chamado schwa (ə). É por isso que \"banana\" em inglês soa \"bə-NA-nə\". Acertar a sílaba forte é mais importante que acertar cada vogal: com a força no lugar errado, o nativo não reconhece a palavra.",
          exemplos: [["banana", "", "bə-NA-nə"], ["computer", "", "com-PU-ter"], ["photograph / photography", "", "PHO-to-graph / pho-TO-gra-phy"]] },
      ],
      erros: ["Ler a palavra do jeito que está escrita, como em português.", "Colocar \"i\" no fim: \"Facebooki\", \"hot-dogui\".", "Trocar TH por T ou F.", "Dar a mesma força a todas as sílabas."],
      pratica: [
        { p: "Como se pronuncia o final de \"book\"?", r: "Seco, no k: \"buk\", sem \"i\" no fim." },
        { p: "Qual a diferença entre \"three\" e \"tree\"?", r: "three (três) tem TH: língua entre os dentes soprando. tree (árvore) começa com t normal." },
        { p: "Em \"computer\", qual é a sílaba forte?", r: "PU: com-PU-ter." },
      ],
    },
  ],
  a1: [
    {
      titulo: "O verbo to be: ser e estar",
      objetivo: "Usar am, is e are para se apresentar, descrever e fazer perguntas.",
      secoes: [
        { t: "Um verbo, dois sentidos", texto: "Em inglês, ser e estar são o mesmo verbo: to be. \"Eu sou brasileiro\" e \"Eu estou cansado\" usam a mesma palavra. O contexto resolve.",
          exemplos: [["I am Brazilian.", "", "Eu sou brasileiro."], ["I am tired.", "", "Eu estou cansado."]] },
        { t: "A conjugação no presente", texto: "Só existem três formas. Decore a tabela: ela aparece em quase toda frase.",
          tabela: [["Pessoa", "Forma", "Contração", "Exemplo"], ["I", "am", "I'm", "I'm a student."], ["you / we / they", "are", "you're, we're, they're", "They're friends."], ["he / she / it", "is", "he's, she's, it's", "She's a teacher."]] },
        { t: "Negativa: só acrescente not", texto: "Coloque not depois do verbo. Na fala, use as contrações isn't e aren't.",
          exemplos: [["I'm not tired.", "", "Não estou cansado."], ["He isn't at home.", "", "Ele não está em casa."], ["We aren't late.", "", "Não estamos atrasados."]] },
        { t: "Pergunta: inverta a ordem", texto: "Para perguntar, o verbo vai para a frente do sujeito. Respostas curtas repetem o verbo: Yes, I am. / No, I'm not.",
          exemplos: [["Are you Brazilian?", "", "Você é brasileiro?"], ["Yes, I am.", "", "Sim, sou."], ["Is she a doctor?", "", "Ela é médica?"], ["No, she isn't.", "", "Não, não é."]] },
        { t: "Profissão pede a/an", texto: "Diferente do português (\"sou professor\"), o inglês exige o artigo antes da profissão: I'm a teacher. Use an antes de som de vogal: an engineer, an actor.",
          exemplos: [["I'm a teacher.", "", "Sou professor."], ["She's an engineer.", "", "Ela é engenheira."]] },
      ],
      erros: ["\"I have 20 years\" → o certo é I am 20 (years old). Idade usa to be.", "\"I am teacher\" → falta o artigo: I am a teacher.", "\"Yes, I'm.\" → contração não pode ficar no fim: Yes, I am.", "\"She are\" → he/she/it sempre com is."],
      pratica: [
        { p: "Complete: They ___ my friends.", r: "are — They are (They're) my friends." },
        { p: "Transforme em pergunta: He is Japanese.", r: "Is he Japanese?" },
        { p: "Como dizer \"Tenho 25 anos\"?", r: "I'm 25 (years old)." },
        { p: "Negue: I am hungry.", r: "I'm not hungry." },
      ],
    },
    {
      titulo: "Artigos, plural e this/that",
      objetivo: "Usar a, an, the, formar o plural e apontar para as coisas.",
      secoes: [
        { t: "a, an e the", texto: "a/an = um, uma (algo não específico). A escolha depende do SOM seguinte, não da letra: a university (som de \"iu\"), an hour (h mudo).\n\nthe = o, a, os, as (algo específico, que os dois sabem qual é). Serve para singular e plural, masculino e feminino.",
          exemplos: [["I have a car.", "", "Tenho um carro."], ["The car is red.", "", "O carro é vermelho."], ["an apple / an hour", "", "uma maçã / uma hora"]] },
        { t: "O plural", texto: "Regra geral: acrescente -s. Depois de s, x, ch, sh: -es. Consoante + y vira -ies. Alguns são irregulares e precisam ser decorados.",
          tabela: [["Singular", "Plural", "Regra"], ["book", "books", "+ s"], ["box", "boxes", "+ es"], ["city", "cities", "y → ies"], ["man / woman", "men / women", "irregular"], ["child", "children", "irregular"], ["person", "people", "irregular"]] },
        { t: "Adjetivo não tem plural", texto: "Em português, \"carros vermelhos\". Em inglês o adjetivo nunca muda e vem antes do substantivo: red cars.",
          exemplos: [["two red cars", "", "dois carros vermelhos"], ["new books", "", "livros novos"]] },
        { t: "this, that, these, those", texto: "Perto de mim: this (singular), these (plural). Longe: that (singular), those (plural).",
          exemplos: [["This is my phone.", "", "Este é o meu telefone."], ["Those are my books.", "", "Aqueles são os meus livros."], ["What is that?", "", "O que é aquilo?"]] },
      ],
      erros: ["\"reds cars\" → adjetivo não vai para o plural: red cars.", "\"a hour\" → an hour (o h é mudo).", "\"The life is good\" → para falar de algo em geral, sem the: Life is good.", "\"peoples\" → people já é plural."],
      pratica: [
        { p: "a ou an? ___ umbrella / ___ uniform", r: "an umbrella / a uniform (uniform começa com som de \"iu\")." },
        { p: "Plural de: bus, baby, foot", r: "buses, babies, feet." },
        { p: "Traduza: \"Estas maçãs são verdes.\"", r: "These apples are green." },
      ],
    },
    {
      titulo: "Presente simples: rotina e fatos",
      objetivo: "Falar do que você faz sempre, com afirmativa, negativa e pergunta.",
      secoes: [
        { t: "Para que serve", texto: "O presente simples fala de hábitos, rotina e verdades gerais: o que você faz sempre, às vezes ou nunca. Não é para o que está acontecendo agora (isso é o presente contínuo, no A2).",
          exemplos: [["I work every day.", "", "Eu trabalho todo dia."], ["Water boils at 100 degrees.", "", "A água ferve a 100 graus."]] },
        { t: "O -s da terceira pessoa", texto: "O verbo é igual para todos, menos he / she / it, que ganham -s. Esse -s é o erro mais comum de brasileiros, até em nível avançado. Preste atenção desde já.",
          tabela: [["Sujeito", "Verbo", "Exemplo"], ["I / you / we / they", "work", "They work in Tokyo."], ["he / she / it", "works", "She works in Tokyo."], ["he / she / it (go, do)", "goes, does", "He goes to school."], ["he / she / it (have)", "has", "She has a car."]] },
        { t: "Negativa e pergunta usam do / does", texto: "O inglês precisa de um verbo auxiliar: do (I, you, we, they) ou does (he, she, it). Quando does aparece, o -s sai do verbo principal: ele já está no does.",
          exemplos: [["I don't eat meat.", "", "Eu não como carne."], ["She doesn't like coffee.", "", "Ela não gosta de café."], ["Do you speak English?", "", "Você fala inglês?"], ["Does he work here?", "", "Ele trabalha aqui?"]] },
        { t: "Advérbios de frequência", texto: "always (sempre), usually (geralmente), often (frequentemente), sometimes (às vezes), never (nunca). Eles vão ANTES do verbo principal, mas DEPOIS do to be.",
          exemplos: [["I always drink coffee.", "", "Sempre tomo café."], ["She is never late.", "", "Ela nunca se atrasa."]] },
      ],
      erros: ["\"She work\" → She works.", "\"He doesn't works\" → He doesn't work (o -s já está no does).", "\"You speak English?\" → na escrita, falta o do: Do you speak English?", "\"I always am tired\" → I am always tired (depois do to be)."],
      pratica: [
        { p: "Complete: My brother ___ (live) in London.", r: "lives." },
        { p: "Negue: He plays soccer.", r: "He doesn't play soccer." },
        { p: "Faça a pergunta: They work on Saturdays.", r: "Do they work on Saturdays?" },
        { p: "Coloque never: I eat fish.", r: "I never eat fish." },
      ],
    },
    {
      titulo: "Perguntas com wh- e preposições de tempo e lugar",
      objetivo: "Perguntar o quê, onde, quando, por quê e usar in, on, at.",
      secoes: [
        { t: "As palavras de pergunta", texto: "what (o quê), who (quem), where (onde), when (quando), why (por quê), how (como), how much (quanto custa / quanto), how many (quantos).\n\nFórmula: palavra de pergunta + auxiliar (do/does ou to be) + sujeito + verbo.",
          exemplos: [["Where do you live?", "", "Onde você mora?"], ["What does she want?", "", "O que ela quer?"], ["Why are you sad?", "", "Por que você está triste?"], ["How much is it?", "", "Quanto custa?"]] },
        { t: "in, on, at para tempo", texto: "Pense num funil, do maior para o menor:\n• in: meses, anos, estações, partes do dia (in May, in 2025, in the morning)\n• on: dias e datas (on Monday, on May 5th)\n• at: horas e momentos exatos (at 7 o'clock, at night, at noon)",
          exemplos: [["I was born in 1995.", "", "Nasci em 1995."], ["See you on Monday.", "", "Até segunda."], ["The class starts at nine.", "", "A aula começa às nove."]] },
        { t: "in, on, at para lugar", texto: "• in: dentro de um espaço (in the box, in Brazil, in the kitchen)\n• on: em cima de uma superfície (on the table, on the wall)\n• at: num ponto ou endereço (at home, at work, at the bus stop)",
          exemplos: [["The keys are on the table.", "", "As chaves estão na mesa."], ["She is at work.", "", "Ela está no trabalho."], ["I live in São Paulo.", "", "Moro em São Paulo."]] },
      ],
      erros: ["\"Where you live?\" → falta o auxiliar: Where do you live?", "\"in Monday\" → on Monday.", "\"in night\" → at night (mas in the morning).", "\"I'm in home\" → I'm at home."],
      pratica: [
        { p: "Pergunte onde ela trabalha.", r: "Where does she work?" },
        { p: "in, on ou at? ___ Christmas day / ___ December / ___ 3 p.m.", r: "on Christmas day / in December / at 3 p.m." },
        { p: "Traduza: \"Ele está no ônibus.\"", r: "He is on the bus. (transporte coletivo usa on)" },
      ],
    },
  ],
  a2: [
    {
      titulo: "Presente contínuo: o que está acontecendo agora",
      objetivo: "Diferenciar \"eu trabalho\" de \"estou trabalhando\" e usar o contínuo para planos.",
      secoes: [
        { t: "A forma", texto: "to be (am/is/are) + verbo com -ing. A regra do -ing: verbo terminado em -e perde o e (make → making); verbo curto de consoante-vogal-consoante dobra a última letra (run → running, sit → sitting).",
          exemplos: [["I'm studying now.", "", "Estou estudando agora."], ["It's raining.", "", "Está chovendo."], ["What are you doing?", "", "O que você está fazendo?"]] },
        { t: "Simples × contínuo", texto: "Simples = hábito (sempre). Contínuo = agora, ou uma fase temporária.\n\nI work in a bank (é meu emprego). I'm working from home this week (é temporário).",
          exemplos: [["I usually drink tea, but today I'm drinking coffee.", "", "Geralmente tomo chá, mas hoje estou tomando café."]] },
        { t: "Verbos que não vão para o -ing", texto: "Verbos de estado (sentimento, opinião, posse) quase nunca usam o contínuo: like, love, want, need, know, understand, believe, have (no sentido de possuir).",
          exemplos: [["I understand.", "", "Estou entendendo / entendo."], ["I want a coffee.", "", "Quero um café."]] },
        { t: "Contínuo para planos combinados", texto: "Para compromissos já marcados, o nativo usa o contínuo com ideia de futuro.",
          exemplos: [["I'm meeting Ana tomorrow.", "", "Vou encontrar a Ana amanhã."], ["We're flying to Tokyo on Friday.", "", "Vamos voar para Tóquio na sexta."]] },
      ],
      erros: ["\"I am agree\" → I agree (agree não usa to be).", "\"I'm understanding\" → I understand.", "\"She working\" → falta o to be: She is working.", "\"runing\" → running (dobra o n)."],
      pratica: [
        { p: "Complete: Listen! The baby ___ (cry).", r: "is crying." },
        { p: "Simples ou contínuo? She ___ (speak) three languages.", r: "speaks (é uma habilidade permanente)." },
        { p: "Traduza: \"Vou jantar com meus pais hoje à noite.\" (combinado)", r: "I'm having dinner with my parents tonight." },
      ],
    },
    {
      titulo: "Passado simples: regulares, irregulares e did",
      objetivo: "Contar o que aconteceu, perguntar e negar no passado.",
      secoes: [
        { t: "Verbos regulares: -ed", texto: "Acrescente -ed: work → worked, play → played. Lembre dos três sons do -ed da aula de Fundamentos: /t/ (worked), /d/ (played), /id/ (wanted).",
          exemplos: [["I worked yesterday.", "", "Trabalhei ontem."], ["She played tennis.", "", "Ela jogou tênis."]] },
        { t: "Os irregulares mais usados", texto: "Não há regra: decore aos poucos. Estes 10 aparecem em quase toda conversa.",
          tabela: [["Verbo", "Passado", "Sentido"], ["be", "was / were", "ser, estar"], ["go", "went", "ir"], ["have", "had", "ter"], ["do", "did", "fazer"], ["get", "got", "conseguir, ficar"], ["see", "saw", "ver"], ["eat", "ate", "comer"], ["buy", "bought", "comprar"], ["say", "said", "dizer"], ["make", "made", "fazer, fabricar"]] },
        { t: "Negativa e pergunta com did", texto: "did serve para todas as pessoas. Quando did aparece, o verbo principal volta à forma normal: o passado já está no did.",
          exemplos: [["I didn't see the movie.", "", "Não vi o filme."], ["Did you buy the book?", "", "Você comprou o livro?"], ["Where did you go?", "", "Aonde você foi?"]] },
        { t: "was / were", texto: "O to be tem dois passados: was (I, he, she, it) e were (you, we, they). Ele NÃO usa did: a negativa é wasn't / weren't e a pergunta inverte a ordem.",
          exemplos: [["It was fun.", "", "Foi divertido."], ["Were you at home?", "", "Você estava em casa?"], ["They weren't there.", "", "Eles não estavam lá."]] },
      ],
      erros: ["\"I didn't went\" → I didn't go.", "\"Did you saw?\" → Did you see?", "\"I goed\" → I went.", "\"Did you were?\" → Were you?"],
      pratica: [
        { p: "Passado de: take, come, write", r: "took, came, wrote." },
        { p: "Negue: She went to the party.", r: "She didn't go to the party." },
        { p: "Pergunte o que ele comeu.", r: "What did he eat?" },
      ],
    },
    {
      titulo: "Futuro: will × going to",
      objetivo: "Escolher a forma certa para planos, decisões na hora e previsões.",
      secoes: [
        { t: "going to: plano já decidido", texto: "Use be going to quando a decisão foi tomada antes de falar, ou quando há uma evidência agora.",
          exemplos: [["I'm going to study tonight.", "", "Vou estudar hoje à noite (já planejei)."], ["Look at the clouds! It's going to rain.", "", "Olha as nuvens! Vai chover."]] },
        { t: "will: decisão na hora, promessa, previsão", texto: "Use will para decidir no momento, oferecer ajuda, prometer ou dar opinião sobre o futuro.",
          exemplos: [["I'll call you later.", "", "Te ligo mais tarde."], ["I'll help you.", "", "Eu te ajudo."], ["I think it will be fine.", "", "Acho que vai dar certo."]] },
        { t: "Forma", texto: "will serve para todas as pessoas, e o verbo fica na forma base. Negativa: won't (will not).",
          tabela: [["", "will", "going to"], ["Afirmativa", "I'll go.", "I'm going to go."], ["Negativa", "I won't go.", "I'm not going to go."], ["Pergunta", "Will you go?", "Are you going to go?"]] },
      ],
      erros: ["\"I will to go\" → I will go (sem to).", "\"I going to\" → falta o to be: I'm going to.", "Usar will para plano antigo: \"I will travel next week\" soa como decisão agora; se já está combinado, prefira I'm going to travel / I'm traveling."],
      pratica: [
        { p: "O telefone toca. Você diz: \"Eu atendo!\"", r: "I'll get it! (decisão na hora → will)" },
        { p: "Você já comprou as passagens: \"Vou viajar em julho.\"", r: "I'm going to travel in July." },
        { p: "Negue: She will come.", r: "She won't come." },
      ],
    },
    {
      titulo: "Comparativos, superlativos e modais can / could / should",
      objetivo: "Comparar coisas e pedir, oferecer e aconselhar.",
      secoes: [
        { t: "Comparar", texto: "Adjetivo curto (1 sílaba, ou 2 terminando em y): -er than / the -est. Adjetivo longo: more … than / the most. Irregulares: good → better → the best; bad → worse → the worst.",
          tabela: [["Adjetivo", "Comparativo", "Superlativo"], ["cheap", "cheaper than", "the cheapest"], ["big", "bigger than", "the biggest"], ["easy", "easier than", "the easiest"], ["expensive", "more expensive than", "the most expensive"], ["good", "better than", "the best"]] },
        { t: "Igualdade", texto: "as + adjetivo + as = tão … quanto. Negativo: not as … as.",
          exemplos: [["Japanese is as difficult as Chinese.", "", "Japonês é tão difícil quanto chinês."], ["This car isn't as fast as that one.", "", "Este carro não é tão rápido quanto aquele."]] },
        { t: "can, could, should", texto: "Modais não recebem -s nem to depois:\n• can = poder, conseguir, saber fazer\n• could = passado de can, ou pedido educado\n• should = deveria (conselho)",
          exemplos: [["I can swim.", "", "Sei nadar."], ["Could you help me?", "", "Você poderia me ajudar?"], ["You should rest.", "", "Você deveria descansar."]] },
      ],
      erros: ["\"more cheaper\" → cheaper (não use os dois).", "\"She cans\" → She can.", "\"You should to rest\" → You should rest.", "\"bigger that\" → bigger than."],
      pratica: [
        { p: "Compare: Tokyo / big / São Paulo", r: "Tokyo is bigger than São Paulo." },
        { p: "Superlativo de beautiful", r: "the most beautiful." },
        { p: "Peça com educação: abrir a janela", r: "Could you open the window, please?" },
      ],
    },
  ],
  b1: [
    {
      titulo: "Present perfect: a ponte entre passado e presente",
      objetivo: "Usar have + particípio para experiências, resultados e ações que continuam.",
      secoes: [
        { t: "A forma", texto: "have / has + particípio passado (a 3ª coluna dos verbos): work → worked, go → gone, see → seen, eat → eaten, be → been.",
          exemplos: [["I have seen this movie.", "", "Já vi este filme."], ["She has finished.", "", "Ela terminou."]] },
        { t: "Uso 1: experiência sem data", texto: "Quando importa SE aconteceu, não QUANDO. Com ever (alguma vez) e never (nunca).",
          exemplos: [["Have you ever been to Japan?", "", "Você já foi ao Japão?"], ["I've never eaten sushi.", "", "Nunca comi sushi."]] },
        { t: "Uso 2: algo que começou e continua", texto: "Com for (duração) e since (ponto de início). O português usa o presente (\"moro aqui há 5 anos\"); o inglês usa o present perfect.",
          exemplos: [["I've lived here for five years.", "", "Moro aqui há cinco anos."], ["She's worked here since 2020.", "", "Ela trabalha aqui desde 2020."]] },
        { t: "Present perfect × passado simples", texto: "Se tem data ou momento terminado (yesterday, in 2019, last week), é passado simples. Sem data, ou num período que ainda não acabou (today, this week), é present perfect.",
          exemplos: [["I went to China in 2019.", "", "Fui à China em 2019."], ["I've been to China twice.", "", "Já fui à China duas vezes."]] },
      ],
      erros: ["\"I have seen it yesterday\" → I saw it yesterday (tem data).", "\"I live here for 5 years\" → I've lived here for 5 years.", "\"since 5 years\" → for 5 years (since é para o ponto de início).", "\"Did you ever go?\" → Have you ever been?"],
      pratica: [
        { p: "for ou since? ___ three hours / ___ Monday", r: "for three hours / since Monday." },
        { p: "Traduza: \"Estudo inglês há dois anos.\"", r: "I've been studying English for two years. (ou I've studied English for two years.)" },
        { p: "Corrija: I have gone to Paris last year.", r: "I went to Paris last year." },
      ],
    },
    {
      titulo: "Condicionais 0 e 1: se…, então…",
      objetivo: "Falar de fatos e de possibilidades reais no futuro.",
      secoes: [
        { t: "Condicional zero: verdades", texto: "if + presente, presente. Para regras e fatos que sempre acontecem.",
          exemplos: [["If you heat ice, it melts.", "", "Se você esquenta gelo, ele derrete."]] },
        { t: "Primeira condicional: possibilidade real", texto: "if + presente, will + verbo. A parte com if usa o PRESENTE, mesmo falando do futuro. Esse é o erro mais comum.",
          exemplos: [["If it rains, I'll stay home.", "", "Se chover, fico em casa."], ["If you don't understand, ask me.", "", "Se não entender, me pergunte."]] },
        { t: "unless, when, as soon as", texto: "unless = a menos que (if … not). when e as soon as seguem a mesma regra: presente na oração do tempo.",
          exemplos: [["I'll go unless it rains.", "", "Vou, a menos que chova."], ["Call me when you arrive.", "", "Me ligue quando chegar."], ["I'll tell you as soon as I know.", "", "Te conto assim que souber."]] },
      ],
      erros: ["\"If it will rain\" → If it rains.", "\"When I will arrive\" → When I arrive.", "Esquecer a vírgula quando o if vem primeiro (na escrita): If it rains, I'll stay."],
      pratica: [
        { p: "Complete: If she ___ (study), she ___ (pass).", r: "If she studies, she will pass." },
        { p: "Troque por unless: I'll go if I'm not tired.", r: "I'll go unless I'm tired." },
      ],
    },
    {
      titulo: "Orações relativas e verbos + -ing / to",
      objetivo: "Ligar ideias com who/which/that e escolher entre gerúndio e infinitivo.",
      secoes: [
        { t: "who, which, that, where", texto: "who = pessoas, which = coisas, that = pessoas ou coisas (mais comum na fala), where = lugares, whose = cujo.",
          exemplos: [["The woman who lives there is a doctor.", "", "A mulher que mora ali é médica."], ["The book that I bought is great.", "", "O livro que comprei é ótimo."], ["This is the restaurant where we met.", "", "Este é o restaurante onde nos conhecemos."]] },
        { t: "Quando o \"que\" some", texto: "Se o que vem depois tem sujeito próprio (I bought, you said), o that pode sumir. É assim que o nativo fala.",
          exemplos: [["The book I bought is great.", "", "O livro que comprei é ótimo."], ["The movie we saw was good.", "", "O filme que vimos foi bom."]] },
        { t: "-ing ou to?", texto: "Não há lógica total: decore em grupos.\n• + -ing: enjoy, finish, avoid, mind, suggest, keep\n• + to: want, need, decide, hope, plan, promise\n• depois de preposição, sempre -ing: interested in learning, good at cooking",
          exemplos: [["I enjoy reading.", "", "Gosto de ler."], ["I decided to stay.", "", "Decidi ficar."], ["Thanks for helping me.", "", "Obrigado por me ajudar."]] },
      ],
      erros: ["\"The man which\" → The man who (pessoa).", "\"I enjoy to read\" → I enjoy reading.", "\"I want going\" → I want to go.", "\"interested in learn\" → interested in learning."],
      pratica: [
        { p: "Complete: The girl ___ called you is my sister.", r: "who (ou that)." },
        { p: "Corrija: I suggest to leave early.", r: "I suggest leaving early." },
        { p: "Junte: I met a man. He speaks five languages.", r: "I met a man who speaks five languages." },
      ],
    },
  ],
  b2: [
    {
      titulo: "Voz passiva",
      objetivo: "Tirar o foco de quem faz e colocá-lo no que é feito.",
      secoes: [
        { t: "Forma", texto: "to be (no tempo certo) + particípio. Quem faz, se aparecer, vem com by.",
          tabela: [["Tempo", "Ativa", "Passiva"], ["Presente", "They make cars here.", "Cars are made here."], ["Passado", "Someone stole my phone.", "My phone was stolen."], ["Present perfect", "They have sold the house.", "The house has been sold."], ["Futuro", "They will build a bridge.", "A bridge will be built."]] },
        { t: "Quando usar", texto: "Quando quem fez é desconhecido, óbvio ou menos importante. É comum em notícias, ciência e textos formais.",
          exemplos: [["English is spoken all over the world.", "", "Inglês é falado no mundo todo."], ["The meeting has been cancelled.", "", "A reunião foi cancelada."]] },
        { t: "get + particípio (informal)", texto: "Na fala, get substitui o to be para coisas que acontecem com alguém: get married (casar), get fired (ser demitido), get hurt (se machucar).",
          exemplos: [["She got promoted.", "", "Ela foi promovida."], ["I got caught in the rain.", "", "Fui pego pela chuva."]] },
      ],
      erros: ["\"The house was build\" → was built (particípio).", "\"It was made for my mother\" (quando ela fez) → made by my mother.", "Usar passiva o tempo todo: em conversa, a voz ativa soa mais natural."],
      pratica: [
        { p: "Passe para a passiva: They clean the office every day.", r: "The office is cleaned every day." },
        { p: "Passe para a passiva: Shakespeare wrote Hamlet.", r: "Hamlet was written by Shakespeare." },
      ],
    },
    {
      titulo: "Segunda e terceira condicional, wish",
      objetivo: "Falar do que não é real: hipóteses, arrependimentos e desejos.",
      secoes: [
        { t: "Segunda: hipótese no presente", texto: "if + passado, would + verbo. Fala de algo imaginário agora. Com to be, o padrão é were para todos (If I were you).",
          exemplos: [["If I were rich, I would travel.", "", "Se eu fosse rico, viajaria."], ["If I were you, I'd accept.", "", "No seu lugar, eu aceitaria."]] },
        { t: "Terceira: arrependimento no passado", texto: "if + had + particípio, would have + particípio. Fala de algo que não aconteceu e não dá mais para mudar.",
          exemplos: [["If I had studied, I would have passed.", "", "Se eu tivesse estudado, teria passado."]] },
        { t: "wish", texto: "wish + passado = desejo sobre o presente. wish + had + particípio = arrependimento sobre o passado.",
          exemplos: [["I wish I could speak Chinese.", "", "Queria saber falar chinês."], ["I wish I had called her.", "", "Queria ter ligado para ela."]] },
      ],
      erros: ["\"If I would have\" → If I had.", "\"If I was you\" é aceito na fala, mas em provas use If I were you.", "\"I wish I can\" → I wish I could."],
      pratica: [
        { p: "Complete: If I ___ (have) time, I ___ (learn) Japanese.", r: "If I had time, I would learn Japanese." },
        { p: "Arrependimento: não fui à festa.", r: "I wish I had gone to the party." },
      ],
    },
    {
      titulo: "Discurso indireto e conectores de argumento",
      objetivo: "Contar o que alguém disse e organizar uma opinião.",
      secoes: [
        { t: "O tempo recua", texto: "Ao relatar, o verbo volta um tempo: presente → passado, will → would, passado → had + particípio. Pronomes e palavras de tempo também mudam (tomorrow → the next day).",
          tabela: [["Ele disse:", "Relato"], ["\"I am tired.\"", "He said he was tired."], ["\"I will come.\"", "He said he would come."], ["\"I saw it.\"", "He said he had seen it."]] },
        { t: "Perguntas e ordens relatadas", texto: "Pergunta relatada tem ordem de afirmação (sem do/did). Sim/não usa if. Ordem usa tell + pessoa + to.",
          exemplos: [["She asked where I lived.", "", "Ela perguntou onde eu morava."], ["He asked if I was okay.", "", "Ele perguntou se eu estava bem."], ["They told me to wait.", "", "Eles me disseram para esperar."]] },
        { t: "Conectores", texto: "Somar: moreover, in addition. Contrastar: however, although, on the other hand. Concluir: therefore, as a result. Exemplificar: for example, such as.\n\nhowever começa frase com vírgula; although liga duas orações.",
          exemplos: [["It's expensive. However, it's worth it.", "", "É caro. No entanto, vale a pena."], ["Although it was late, we kept working.", "", "Embora fosse tarde, continuamos trabalhando."]] },
      ],
      erros: ["\"She asked where did I live\" → where I lived.", "\"He said me\" → He told me / He said (to me).", "\"Although…, but…\" → não use os dois juntos."],
      pratica: [
        { p: "Relate: \"I love this city,\" she said.", r: "She said (that) she loved that city." },
        { p: "Relate: \"Do you speak English?\" he asked me.", r: "He asked me if I spoke English." },
      ],
    },
  ],
  c1: [
    {
      titulo: "Ênfase, inversão e nuance",
      objetivo: "Soar natural e sofisticado: destacar ideias como um nativo.",
      secoes: [
        { t: "Frases clivadas (It is… that / What… is)", texto: "Para destacar uma parte da frase, separe-a. Muito usado para corrigir ou enfatizar.",
          exemplos: [["It was John who called, not Mary.", "", "Foi o John que ligou, não a Mary."], ["What I need is a break.", "", "O que eu preciso é de uma pausa."]] },
        { t: "Inversão (registro formal)", texto: "Depois de expressões negativas no começo da frase, o auxiliar vem antes do sujeito, como numa pergunta.",
          exemplos: [["Never have I seen such a mess.", "", "Nunca vi tamanha bagunça."], ["Not only is it cheap, but it's also good.", "", "Não só é barato, como também é bom."], ["Had I known, I would have come.", "", "Se eu soubesse, teria vindo."]] },
        { t: "Suavizar e ser diplomático", texto: "O inglês profissional evita soar direto demais. Use modais, perguntas negativas e palavras que suavizam.",
          exemplos: [["I was wondering if you could help me.", "", "Queria saber se você poderia me ajudar."], ["Wouldn't it be better to wait?", "", "Não seria melhor esperar?"], ["It might be worth considering…", "", "Talvez valha a pena considerar…"]] },
      ],
      erros: ["\"Never I have seen\" → Never have I seen.", "Ser direto demais em e-mails: \"I want the report\" → Could you send me the report?"],
      pratica: [
        { p: "Enfatize: I need more time.", r: "What I need is more time." },
        { p: "Deixe diplomático: Send me the file.", r: "Could you send me the file, please? / Would you mind sending me the file?" },
      ],
    },
    {
      titulo: "Phrasal verbs e expressões idiomáticas",
      objetivo: "Entender o inglês do dia a dia, que usa verbos + partículas em vez de palavras latinas.",
      secoes: [
        { t: "O que são", texto: "Verbo + partícula (up, out, off, on…) com sentido novo. O nativo prefere \"find out\" a \"discover\", \"give up\" a \"abandon\". Aprenda pelo contexto, em frases.",
          tabela: [["Phrasal verb", "Sentido", "Exemplo"], ["find out", "descobrir", "I found out the truth."], ["give up", "desistir", "Don't give up."], ["figure out", "entender, resolver", "I can't figure it out."], ["look forward to", "aguardar com expectativa", "I look forward to hearing from you."], ["come up with", "inventar, ter (ideia)", "She came up with a plan."], ["run out of", "ficar sem", "We ran out of time."]] },
        { t: "Separáveis", texto: "Muitos aceitam o objeto no meio. Com pronome (it, them), ele TEM de ir no meio.",
          exemplos: [["Turn off the light. / Turn the light off.", "", "Apague a luz."], ["Turn it off.", "", "Apague-a. (nunca \"turn off it\")"]] },
        { t: "Idioms", texto: "Expressões fixas, que não se traduzem palavra por palavra: break the ice (quebrar o gelo), a piece of cake (moleza), hit the nail on the head (acertar em cheio), under the weather (meio doente).",
          exemplos: [["That exam was a piece of cake.", "", "A prova foi moleza."], ["I'm a bit under the weather today.", "", "Estou meio indisposto hoje."]] },
      ],
      erros: ["\"Turn off it\" → Turn it off.", "Traduzir idioms ao pé da letra do português: \"It's cake of the good\" não existe."],
      pratica: [
        { p: "Troque pelo phrasal verb: We have no more milk.", r: "We've run out of milk." },
        { p: "O que significa \"I'll figure it out\"?", r: "Vou dar um jeito / vou descobrir como resolver." },
      ],
    },
  ],
};
